import re

with open("src/tools/narrator.rs", "r") as f:
    lines = f.readlines()

out = []
in_add_stmt = False
for i, line in enumerate(lines):
    if line.startswith("fn add_statement(table: &mut Table, stmt: &AnalyzedStatement, level: usize) {"):
        in_add_stmt = True
        out.append(line)
        out.append("    let prefix = indent(level);\n\n")
        out.append("    let (act, script, notes) = describe_statement(stmt);\n")
        out.append('    if act == "EMPTY" { return; }\n\n')
        out.append("    let act_color = match act.as_str() {\n")
        out.append('        "BIND" => Color::Blue,\n')
        out.append('        "SET" => Color::Yellow,\n')
        out.append('        "PRINT" => Color::Green,\n')
        out.append('        "EXPR" => Color::DarkGrey,\n')
        out.append('        "QUERY" => Color::Magenta,\n')
        out.append('        "IF" | "WHILE" | "FOR" | "MATCH" => Color::Magenta,\n')
        out.append('        "BREAK" | "RET" => Color::Red,\n')
        out.append('        "CONT" => Color::Yellow,\n')
        out.append('        "DEF" | "TYPE" | "TRAIT" | "IMPL" => Color::Cyan,\n')
        out.append('        "TEST" => Color::Yellow,\n')
        out.append("        _ => Color::White,\n")
        out.append("    };\n\n")
        out.append("    let notes_color = match act.as_str() {\n")
        out.append('        "BIND" => if notes == "Mutable" { Color::Red } else { Color::Green },\n')
        out.append('        "SET" => Color::Red,\n')
        out.append('        "PRINT" => Color::Cyan,\n')
        out.append('        "EXPR" => Color::DarkGrey,\n')
        out.append('        "QUERY" => Color::Yellow,\n')
        out.append('        "IF" | "WHILE" | "FOR" | "MATCH" => Color::Magenta,\n')
        out.append('        "BREAK" | "RET" => Color::Red,\n')
        out.append('        "CONT" => Color::Yellow,\n')
        out.append('        "DEF" | "IMPL" => Color::Cyan,\n')
        out.append('        "TYPE" => Color::Cyan,\n')
        out.append('        "TRAIT" => Color::Cyan,\n')
        out.append('        "TEST" => Color::Yellow,\n')
        out.append("        _ => Color::White,\n")
        out.append("    };\n\n")
        out.append("    table.add_row(vec![\n")
        out.append("        Cell::new(&act).fg(act_color),\n")
        out.append('        Cell::new(format!("{}{}", prefix, script)),\n')
        out.append("        Cell::new(&notes).fg(notes_color),\n")
        out.append("    ]);\n\n")
        out.append("    // Process nested structures\n")
        out.append("    match stmt {\n")
        out.append("        AnalyzedStatement::If { then_body, else_body, .. } => {\n")
        out.append("            for nested_stmt in then_body {\n")
        out.append("                add_statement(table, nested_stmt, level + 1);\n")
        out.append("            }\n")
        out.append("            if let Some(else_stmts) = else_body {\n")
        out.append("                table.add_row(vec![\n")
        out.append('                    Cell::new("ELSE").fg(Color::Magenta),\n')
        out.append('                    Cell::new(format!("{}Otherwise:", prefix)),\n')
        out.append('                    Cell::new("Branch").fg(Color::Magenta),\n')
        out.append("                ]);\n")
        out.append("                for nested_stmt in else_stmts {\n")
        out.append("                    add_statement(table, nested_stmt, level + 1);\n")
        out.append("                }\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::While { body, .. } | AnalyzedStatement::For { body, .. } => {\n")
        out.append("            for nested_stmt in body {\n")
        out.append("                add_statement(table, nested_stmt, level + 1);\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::Match { arms, .. } => {\n")
        out.append("            for (pattern, body) in arms {\n")
        out.append("                table.add_row(vec![\n")
        out.append('                    Cell::new("ARM").fg(Color::DarkGrey),\n')
        out.append('                    Cell::new(format!("{}  If {}:", prefix, tell_expr(pattern))),\n')
        out.append('                    Cell::new("Case").fg(Color::DarkGrey),\n')
        out.append("                ]);\n")
        out.append("                for nested_stmt in body {\n")
        out.append("                    add_statement(table, nested_stmt, level + 2);\n")
        out.append("                }\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::FunctionDef { body, .. } => {\n")
        out.append("            for nested_stmt in body {\n")
        out.append("                add_statement(table, nested_stmt, level + 1);\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::TypeDefinition { fields, .. } => {\n")
        out.append("            for (name, ty) in fields {\n")
        out.append("                table.add_row(vec![\n")
        out.append('                    Cell::new("FIELD").fg(Color::DarkGrey),\n')
        out.append('                    Cell::new(format!("{}  `{}` of type {}", prefix, name, tell_type(ty))),\n')
        out.append('                    Cell::new("Data").fg(Color::DarkGrey),\n')
        out.append("                ]);\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::TraitDefinition { methods, .. } => {\n")
        out.append("            for method in methods {\n")
        out.append("                table.add_row(vec![\n")
        out.append('                    Cell::new("REQ").fg(Color::DarkGrey),\n')
        out.append('                    Cell::new(format!("{}  Requires method `{}`", prefix, method.name)),\n')
        out.append('                    Cell::new("Contract").fg(Color::DarkGrey),\n')
        out.append("                ]);\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::TraitImplementation { methods, .. } => {\n")
        out.append("            for func in methods {\n")
        out.append("                table.add_row(vec![\n")
        out.append('                    Cell::new("METH").fg(Color::Cyan),\n')
        out.append('                    Cell::new(format!("{}  Method `{}`", prefix, func.name)),\n')
        out.append('                    Cell::new("Function").fg(Color::Cyan),\n')
        out.append("                ]);\n")
        out.append("                for nested_stmt in &func.body {\n")
        out.append("                    add_statement(table, nested_stmt, level + 2);\n")
        out.append("                }\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        AnalyzedStatement::TestDeclaration { body, .. } => {\n")
        out.append("            for nested_stmt in body {\n")
        out.append("                add_statement(table, nested_stmt, level + 1);\n")
        out.append("            }\n")
        out.append("        }\n")
        out.append("        _ => {}\n")
        out.append("    }\n")
        out.append("}\n")
        continue

    if in_add_stmt:
        if line.startswith("pub fn tell_expr"):
            in_add_stmt = False
            out.append(line)
        continue

    out.append(line)

with open("src/tools/narrator.rs", "w") as f:
    f.writelines(out)
