//! The Expression Builder (Ὁ Δομήτωρ Ἔργων)
//!
//! This module acts as the builder for expressions and terms within a sentence.
//! While `statements.rs` handles the high-level flow (like `If` or `While`),
//! this module drills down into the core actions, literals, and function calls
//! that actually do the work.
//!
//! # Why it exists
//!
//! In ΓΛΩΣΣΑ, an expression isn't just `a + b`. It involves navigating Greek
//! numerals (like `ιε` for 15), strings wrapped in guillemets (`«...»`), and
//! deeply nested phrases. This module translates the generic, untyped parse tree
//! generated by Pest into strongly-typed `Expr` variants. By isolating expression
//! construction, we keep the main parser module clean and focused on file-level structure.
//!
//! # Note
//!
//! These functions are primarily internal to the `parser` crate, invoked by
//! [`crate::parser::statements`] or [`crate::parser::parse`].

use crate::ast::*;
use crate::parser::build_statement;
use crate::parser::common::{ParseError, parse_number_literal};
use crate::parser::grammar::Rule;
use pest::iterators::Pair;

/// Builds an expression from a grammar pair.
///
/// ⚡ Bolt Optimization: Uses `Vec::with_capacity` based on the inner pairs length.
/// This prevents O(log N) heap reallocations when parsing complex expressions,
/// directly improving the compiler's parsing phase throughput.
pub(crate) fn build_expression(pair: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    let inner_pairs = pair.into_inner();
    let mut terms = Vec::with_capacity(inner_pairs.len());

    for inner in inner_pairs {
        if inner.as_rule() == Rule::term {
            terms.push(build_term(inner)?);
        }
    }

    // If there's only one term, return it directly
    if terms.len() == 1 {
        Ok(terms.into_iter().next().ok_or(ParseError::EmptyTerm)?)
    } else {
        // Multiple terms form a phrase (e.g., "χαῖρε κόσμε λέγε")
        Ok(Expr::Phrase(terms)) // Empty terms vector returns an empty Phrase
    }
}

pub(crate) fn build_term(pair: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    let inner = pair.into_inner().next().ok_or(ParseError::EmptyTerm)?;

    match inner.as_rule() {
        Rule::block => build_block_expr(inner),
        Rule::array_literal => build_array_literal_expr(inner),
        Rule::indexed_word => build_indexed_word_expr(inner),
        Rule::parenthesized_expr => {
            // Unwrap the parentheses and build the inner expression
            let expr_pair = inner.into_inner().next().ok_or(ParseError::EmptyTerm)?;
            build_expression(expr_pair)
        }
        Rule::unwrap_expr => build_unwrap_expr(inner),
        // Literals
        Rule::string_literal | Rule::number_literal | Rule::boolean_literal | Rule::greek_word => {
            build_literal(inner)
        }
        _ => Err(ParseError::UnexpectedRule(format!("{:?}", inner.as_rule()))),
    }
}

/// Builds a block expression from a grammar pair.
///
/// ⚡ Bolt Optimization: Uses `Vec::with_capacity` based on the number of statements.
/// This minimizes heap allocations for typical block bodies (functions, loops).
fn build_block_expr(inner: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    let inner_pairs = inner.into_inner();
    let mut statements = Vec::with_capacity(inner_pairs.len());
    for stmt_pair in inner_pairs {
        if stmt_pair.as_rule() == Rule::statement {
            statements.push(build_statement(stmt_pair)?);
        }
    }
    Ok(Expr::Block(statements))
}

/// Builds an array literal expression.
///
/// ⚡ Bolt Optimization: Uses `Vec::with_capacity` when the number of elements is known.
/// This prevents intermediate array reallocations for large array literals.
fn build_array_literal_expr(inner: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    for child in inner.into_inner() {
        if child.as_rule() == Rule::array_elements {
            let elem_pairs = child.into_inner();
            let mut elements = Vec::with_capacity(elem_pairs.len());
            for elem in elem_pairs {
                if elem.as_rule() == Rule::array_element {
                    elements.push(build_array_element(elem)?);
                }
            }
            return Ok(Expr::ArrayLiteral(elements));
        }
    }
    Ok(Expr::ArrayLiteral(Vec::new())) // Empty array literal
}

fn build_indexed_word_expr(inner: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    let mut parts = inner.into_inner();
    // First is the greek_word (array name)
    let array_word = parts.next().ok_or(ParseError::EmptyTerm)?;
    let array = Expr::Word(Word {
        original: array_word.as_str().into(),
        normalized: crate::text::normalize_greek(array_word.as_str()),
    });
    // Second is the index_expr
    let index_pair = parts.next().ok_or(ParseError::EmptyTerm)?;
    let index_inner = index_pair
        .into_inner()
        .next()
        .ok_or(ParseError::EmptyTerm)?;
    let index = match index_inner.as_rule() {
        Rule::number_literal => {
            let value = parse_number_literal(index_inner.as_str())?;
            Expr::NumberLiteral(value)
        }
        Rule::greek_word => Expr::Word(Word {
            original: index_inner.as_str().into(),
            normalized: crate::text::normalize_greek(index_inner.as_str()),
        }),
        _ => {
            return Err(ParseError::UnexpectedRule(format!(
                "{:?}",
                index_inner.as_rule()
            )));
        }
    };
    Ok(Expr::IndexAccess {
        array: Box::new(array),
        index: Box::new(index),
    })
}

fn build_unwrap_expr(inner: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    // Extract the word from "word!"
    let word_pair = inner.into_inner().next().ok_or(ParseError::EmptyTerm)?;
    let word = Expr::Word(Word {
        original: word_pair.as_str().into(),
        normalized: crate::text::normalize_greek(word_pair.as_str()),
    });
    Ok(Expr::UnaryOp {
        op: UnaryOperator::Unwrap,
        operand: Box::new(word),
    })
}

fn build_array_element(pair: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    let inner = pair.into_inner().next().ok_or(ParseError::EmptyTerm)?;
    build_literal(inner)
}

fn build_literal(pair: Pair<'_, Rule>) -> Result<Expr, ParseError> {
    match pair.as_rule() {
        Rule::string_literal => {
            let content = pair
                .into_inner()
                .find(|p| p.as_rule() == Rule::string_content)
                .map(|p| p.as_str().to_string())
                .unwrap_or_default();
            Ok(Expr::StringLiteral(content))
        }
        Rule::number_literal => {
            let value = parse_number_literal(pair.as_str())?;
            Ok(Expr::NumberLiteral(value))
        }
        Rule::boolean_literal => {
            let normalized = crate::text::normalize_greek(pair.as_str());
            let value = normalized == "αληθες";
            Ok(Expr::BooleanLiteral(value))
        }
        Rule::greek_word => Ok(Expr::Word(Word {
            original: pair.as_str().into(),
            normalized: crate::text::normalize_greek(pair.as_str()),
        })),
        _ => Err(ParseError::UnexpectedRule(format!(
            "Not a literal: {:?}",
            pair.as_rule()
        ))),
    }
}
