//! The Scribe (ὁ Γραμματεύς)
//!
//! A tool that generates Markdown documentation from Glossa source code.
//! It analyzes the semantic structure and produces a readable report.

use crate::semantic::{AnalyzedProgram, GlossaType, StatementKind};

/// The Scribe - Documentation Generator
pub struct Scribe;

impl Scribe {
    /// Create a new Scribe
    pub fn new() -> Self {
        Scribe
    }

    /// Generate Markdown documentation for the analyzed program
    pub fn render(&self, program: &AnalyzedProgram) -> String {
        let mut doc = String::new();

        doc.push_str("# ΓΛΩΣΣΑ Documentation\n\n");
        doc.push_str("Generated by **The Scribe** (ὁ Γραμματεύς)\n\n");

        // Collect items by kind
        let mut types = Vec::new();
        let mut traits = Vec::new();
        let mut functions = Vec::new();
        let mut tests = Vec::new();

        for stmt in &program.statements {
            match &stmt.kind {
                StatementKind::TypeDefinition { name, fields } => types.push((name, fields)),
                StatementKind::TraitDefinition { name, methods } => traits.push((name, methods)),
                StatementKind::FunctionDef {
                    name,
                    params,
                    return_type,
                    ..
                } => {
                    functions.push((name, params, return_type));
                }
                StatementKind::TestDeclaration { name, .. } => tests.push(name),
                _ => {}
            }
        }

        // Render Types
        if !types.is_empty() {
            doc.push_str("## Types (Εἴδη)\n\n");
            for (name, fields) in types {
                doc.push_str(&format!("### {}\n\n", name));
                if fields.is_empty() {
                    doc.push_str("*No fields.*\n\n");
                } else {
                    doc.push_str("| Field (Greek) | Type (Greek) | Type (Internal) |\n");
                    doc.push_str("|---|---|---|\n");
                    for (field_name, field_type) in fields {
                        doc.push_str(&format!(
                            "| {} | {} | `{:?}` |\n",
                            field_name,
                            field_type.to_greek(),
                            field_type
                        ));
                    }
                    doc.push('\n');
                }
            }
        }

        // Render Traits
        if !traits.is_empty() {
            doc.push_str("## Traits (Χαρακτῆρες)\n\n");
            for (name, methods) in traits {
                doc.push_str(&format!("### {}\n\n", name));
                if methods.is_empty() {
                    doc.push_str("*No methods.*\n\n");
                } else {
                    doc.push_str("| Method | Parameters |\n");
                    doc.push_str("|---|---|\n");
                    for method in methods {
                        let params: Vec<String> =
                            method.params.iter().map(|(n, _)| n.to_string()).collect();
                        doc.push_str(&format!("| {} | {} |\n", method.name, params.join(", ")));
                    }
                    doc.push('\n');
                }
            }
        }

        // Render Functions
        if !functions.is_empty() {
            doc.push_str("## Functions (Λειτουργίες)\n\n");
            for (name, params, return_type) in functions {
                doc.push_str(&format!("### {}\n\n", name));

                if let Some(rt) = return_type {
                    doc.push_str(&format!("**Returns:** {} (`{:?}`)\n\n", rt.to_greek(), rt));
                }

                if params.is_empty() {
                    doc.push_str("*No parameters.*\n\n");
                } else {
                    doc.push_str("| Parameter | Type | Type (Internal) |\n");
                    doc.push_str("|---|---|---|\n");
                    for (param_name, param_type) in params {
                        let pt = param_type.clone().unwrap_or(GlossaType::Unknown);
                        doc.push_str(&format!(
                            "| {} | {} | `{:?}` |\n",
                            param_name,
                            pt.to_greek(),
                            pt
                        ));
                    }
                    doc.push('\n');
                }
            }
        }

        // Render Tests
        if !tests.is_empty() {
            doc.push_str("## Tests (Δοκιμαί)\n\n");
            for name in tests {
                doc.push_str(&format!("- {}\n", name));
            }
            doc.push('\n');
        }

        doc
    }
}

impl Default for Scribe {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;
    use crate::semantic::analyze_program;

    #[test]
    fn test_scribe_types() {
        let source = "εἶδος Χρήστης ὁρίζειν { ὄνομα ὀνόματος. ηλικία ἀριθμοῦ. }.";
        let ast = parse(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();

        let scribe = Scribe::new();
        let doc = scribe.render(&analyzed);

        println!("{}", doc);
        assert!(doc.contains("## Types"));
        assert!(doc.contains("### χρηστης"));
        assert!(doc.contains("| ονομα | ὄνομα | `String` |"));
        assert!(doc.contains("| ηλικια | ἀριθμός | `Number` |"));
    }

    #[test]
    fn test_scribe_functions() {
        let source = "πρόσθεσις ὁρίζειν τῷ α ἀριθμοῦ· α 1 συν δός.";
        let ast = parse(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();

        let scribe = Scribe::new();
        let doc = scribe.render(&analyzed);

        println!("{}", doc);
        assert!(doc.contains("## Functions"));
        assert!(doc.contains("### προσθεσις"));
        assert!(doc.contains("| α | ἀριθμός | `Number` |"));
    }
}
