//! Rust code generation
//!
//! Translates HIR to Rust source code using the `quote` crate.

use crate::ir::{HirProgram, HirStatement, HirExpr, BinOp};
use quote::{quote, format_ident};
use proc_macro2::TokenStream;

/// Generate Rust code from a HIR program
pub fn generate_rust(hir: &HirProgram) -> String {
    let statements: Vec<TokenStream> = hir.statements.iter()
        .map(generate_statement)
        .collect();

    let output = quote! {
        fn main() {
            #(#statements)*
        }
    };

    output.to_string()
}

/// Generate a complete Rust file with proper formatting
pub fn generate_rust_file(hir: &HirProgram) -> String {
    let code = generate_rust(hir);

    // Add a comment header
    format!(
        "// Generated by ΓΛΩΣΣΑ compiler\n// Αὐτόματος κῶδιξ ἀπὸ ΓΛΩΣΣΑ\n\n{}",
        code
    )
}

fn generate_statement(stmt: &HirStatement) -> TokenStream {
    match stmt {
        HirStatement::Let { name, value, mutable } => {
            let name_ident = format_ident!("{}", sanitize_name(name));
            let value_tokens = generate_expr(value);

            if *mutable {
                quote! { let mut #name_ident = #value_tokens; }
            } else {
                quote! { let #name_ident = #value_tokens; }
            }
        }

        HirStatement::Print { args } => {
            if args.is_empty() {
                quote! { println!(); }
            } else if args.len() == 1 {
                let arg = generate_expr(&args[0]);
                // Use Display formatting for the argument
                match &args[0] {
                    HirExpr::StringLit(_) => quote! { println!("{}", #arg); },
                    HirExpr::Var(_) => quote! { println!("{}", #arg); },
                    _ => quote! { println!("{}", #arg); },
                }
            } else {
                // Multiple args - join with space
                let arg_tokens: Vec<TokenStream> = args.iter()
                    .map(generate_expr)
                    .collect();
                quote! { println!("{}", vec![#(format!("{}", #arg_tokens)),*].join(" ")); }
            }
        }

        HirStatement::Expr(expr) => {
            let expr_tokens = generate_expr(expr);
            quote! { #expr_tokens; }
        }

        HirStatement::If { condition, then_body, else_body } => {
            let cond = generate_expr(condition);
            let then_stmts: Vec<TokenStream> = then_body.iter()
                .map(generate_statement)
                .collect();

            match else_body {
                Some(else_stmts) => {
                    let else_tokens: Vec<TokenStream> = else_stmts.iter()
                        .map(generate_statement)
                        .collect();
                    quote! {
                        if #cond {
                            #(#then_stmts)*
                        } else {
                            #(#else_tokens)*
                        }
                    }
                }
                None => {
                    quote! {
                        if #cond {
                            #(#then_stmts)*
                        }
                    }
                }
            }
        }

        HirStatement::While { condition, body } => {
            let cond = generate_expr(condition);
            let body_stmts: Vec<TokenStream> = body.iter()
                .map(generate_statement)
                .collect();
            quote! {
                while #cond {
                    #(#body_stmts)*
                }
            }
        }

        HirStatement::For { variable, iterator, body } => {
            let var_ident = format_ident!("{}", sanitize_name(variable));
            let iter = generate_expr(iterator);
            let body_stmts: Vec<TokenStream> = body.iter()
                .map(generate_statement)
                .collect();
            quote! {
                for #var_ident in #iter {
                    #(#body_stmts)*
                }
            }
        }

        HirStatement::Match { scrutinee, arms } => {
            let scrut = generate_expr(scrutinee);
            let arm_tokens: Vec<TokenStream> = arms.iter()
                .map(|(pattern, body)| {
                    // Check if pattern is wildcard (represented as BoolLit(true))
                    let pat = if matches!(pattern, HirExpr::BoolLit(true)) {
                        // Generate wildcard pattern
                        quote! { _ }
                    } else {
                        generate_expr(pattern)
                    };
                    let body_stmts: Vec<TokenStream> = body.iter()
                        .map(generate_statement)
                        .collect();
                    quote! { #pat => { #(#body_stmts)* } }
                })
                .collect();
            quote! {
                match #scrut {
                    #(#arm_tokens),*
                }
            }
        }

        HirStatement::Break => quote! { break; },

        HirStatement::Continue => quote! { continue; },

        HirStatement::Return(expr) => {
            match expr {
                Some(e) => {
                    let value = generate_expr(e);
                    quote! { return #value; }
                }
                None => quote! { return; }
            }
        }
    }
}

fn generate_expr(expr: &HirExpr) -> TokenStream {
    match expr {
        HirExpr::StringLit(s) => {
            quote! { #s }
        }

        HirExpr::IntLit(n) => {
            quote! { #n }
        }

        HirExpr::BoolLit(b) => {
            quote! { #b }
        }

        HirExpr::ArrayLit(elements) => {
            let elem_tokens: Vec<TokenStream> = elements.iter()
                .map(generate_expr)
                .collect();
            quote! { vec![#(#elem_tokens),*] }
        }

        HirExpr::Index { array, index } => {
            let array_tokens = generate_expr(array);
            let index_tokens = generate_expr(index);
            quote! { #array_tokens[#index_tokens] }
        }

        HirExpr::Var(name) => {
            let name_ident = format_ident!("{}", sanitize_name(name));
            quote! { #name_ident }
        }

        HirExpr::Field { object, field } => {
            let obj = generate_expr(object);
            let field_ident = format_ident!("{}", sanitize_name(field));
            quote! { #obj.#field_ident }
        }

        HirExpr::MethodCall { receiver, method, args } => {
            let recv = generate_expr(receiver);
            let method_ident = format_ident!("{}", sanitize_name(method));
            let arg_tokens: Vec<TokenStream> = args.iter()
                .map(generate_expr)
                .collect();
            quote! { #recv.#method_ident(#(#arg_tokens),*) }
        }

        HirExpr::Call { func, args } => {
            let func_ident = format_ident!("{}", sanitize_name(func));
            let arg_tokens: Vec<TokenStream> = args.iter()
                .map(generate_expr)
                .collect();
            quote! { #func_ident(#(#arg_tokens),*) }
        }

        HirExpr::BinOp { op, left, right } => {
            let left_tokens = generate_expr(left);
            let right_tokens = generate_expr(right);

            match op {
                BinOp::Add => quote! { (#left_tokens + #right_tokens) },
                BinOp::Sub => quote! { (#left_tokens - #right_tokens) },
                BinOp::Mul => quote! { (#left_tokens * #right_tokens) },
                BinOp::Div => quote! { (#left_tokens / #right_tokens) },
                BinOp::Mod => quote! { (#left_tokens % #right_tokens) },
                BinOp::Eq => quote! { (#left_tokens == #right_tokens) },
                BinOp::Ne => quote! { (#left_tokens != #right_tokens) },
                BinOp::Lt => quote! { (#left_tokens < #right_tokens) },
                BinOp::Le => quote! { (#left_tokens <= #right_tokens) },
                BinOp::Gt => quote! { (#left_tokens > #right_tokens) },
                BinOp::Ge => quote! { (#left_tokens >= #right_tokens) },
                BinOp::And => quote! { (#left_tokens && #right_tokens) },
                BinOp::Or => quote! { (#left_tokens || #right_tokens) },
            }
        }

        HirExpr::Ref { mutable, expr } => {
            let inner = generate_expr(expr);
            if *mutable {
                quote! { &mut #inner }
            } else {
                quote! { &#inner }
            }
        }

        HirExpr::Range { start, end, inclusive } => {
            let start_tokens = generate_expr(start);
            let end_tokens = generate_expr(end);
            if *inclusive {
                quote! { (#start_tokens..=#end_tokens) }
            } else {
                quote! { (#start_tokens..#end_tokens) }
            }
        }
    }
}

/// Sanitize a Greek name for use as a Rust identifier
///
/// Greek letters are mapped to Latin equivalents or transliterated
fn sanitize_name(name: &str) -> String {
    // Map single Greek letters to their names
    if name.len() <= 2 {
        // Could be a single Greek letter (2 bytes for UTF-8)
        match name {
            "α" => return "alpha".to_string(),
            "β" => return "beta".to_string(),
            "γ" => return "gamma".to_string(),
            "δ" => return "delta".to_string(),
            "ε" => return "epsilon".to_string(),
            "ζ" => return "zeta".to_string(),
            "η" => return "eta".to_string(),
            "θ" => return "theta".to_string(),
            "ι" => return "iota".to_string(),
            "κ" => return "kappa".to_string(),
            "λ" => return "lambda".to_string(),
            "μ" => return "mu".to_string(),
            "ν" => return "nu".to_string(),
            "ξ" => return "xi".to_string(),
            "ο" => return "omicron".to_string(),
            "π" => return "pi".to_string(),
            "ρ" => return "rho".to_string(),
            "σ" | "ς" => return "sigma".to_string(),
            "τ" => return "tau".to_string(),
            "υ" => return "upsilon".to_string(),
            "φ" => return "phi".to_string(),
            "χ" => return "chi".to_string(),
            "ψ" => return "psi".to_string(),
            "ω" => return "omega".to_string(),
            _ => {}
        }
    }

    // Transliterate the full name
    transliterate(name)
}

/// Transliterate Greek to Latin characters
fn transliterate(greek: &str) -> String {
    let mut result = String::new();

    for c in greek.chars() {
        let trans = match c {
            'α' => "a",
            'β' => "b",
            'γ' => "g",
            'δ' => "d",
            'ε' => "e",
            'ζ' => "z",
            'η' => "e",
            'θ' => "th",
            'ι' => "i",
            'κ' => "k",
            'λ' => "l",
            'μ' => "m",
            'ν' => "n",
            'ξ' => "x",
            'ο' => "o",
            'π' => "p",
            'ρ' => "r",
            'σ' | 'ς' => "s",
            'τ' => "t",
            'υ' => "u",
            'φ' => "ph",
            'χ' => "ch",
            'ψ' => "ps",
            'ω' => "o",
            _ => {
                result.push(c);
                continue;
            }
        };
        result.push_str(trans);
    }

    // Ensure it starts with a letter or underscore (valid Rust identifier)
    if result.chars().next().map(|c| c.is_numeric()).unwrap_or(true) {
        format!("_{}", result)
    } else {
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::build_ast;
    use crate::semantic::analyze_program;
    use crate::ir::lower_to_hir;

    fn compile(source: &str) -> String {
        let ast = build_ast(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();
        let hir = lower_to_hir(&analyzed);
        generate_rust(&hir)
    }

    #[test]
    fn test_generate_hello() {
        let code = compile("«χαῖρε» λέγε.");
        // quote! generates `println !` with space
        assert!(code.contains("println"), "Expected println in: {}", code);
        assert!(code.contains("χαῖρε"));
    }

    #[test]
    fn test_generate_binding() {
        let code = compile("ξ πέντε ἔστω.");
        assert!(code.contains("let xi"));
        assert!(code.contains("5"));
    }

    #[test]
    fn test_generate_number() {
        let code = compile("42 λέγε.");
        assert!(code.contains("println"), "Expected println in: {}", code);
        assert!(code.contains("42"));
    }

    #[test]
    fn test_sanitize_greek_letter() {
        assert_eq!(sanitize_name("ξ"), "xi");
        assert_eq!(sanitize_name("α"), "alpha");
        assert_eq!(sanitize_name("ω"), "omega");
    }

    #[test]
    fn test_transliterate() {
        assert_eq!(transliterate("χρηστος"), "chrestos");
        assert_eq!(transliterate("λογος"), "logos");
        assert_eq!(transliterate("φιλοσοφια"), "philosophia");
    }

    #[test]
    fn test_generate_full_program() {
        let code = compile("ξ πέντε ἔστω. ξ λέγε.");
        assert!(code.contains("let xi = 5"), "Expected binding in: {}", code);
        assert!(code.contains("println"), "Expected println in: {}", code);
    }
}
