//! Bibliotheca (Βιβλιοθήκη) - Documentation Generator
//!
//! This module generates documentation for Glossa programs.
//! It extracts types, traits, functions, and tests, and formats them as a Markdown document.

use crate::semantic::{AnalyzedProgram, AnalyzedStatement};
use std::fmt::Write;

/// Generate documentation for an analyzed program
pub fn generate_docs(program: &AnalyzedProgram, filename: &str) -> String {
    let mut output = String::new();

    // Header
    writeln!(output, "# Βιβλιοθήκη (Library) - {}", filename).unwrap();
    writeln!(output, "\n*Generated by Glossa Bibliotheca*\n").unwrap();

    // Table of Contents
    writeln!(output, "## Περιεχόμενα (Contents)").unwrap();
    if has_types(program) {
        writeln!(output, "- [Εἴδη (Types)](#εἴδη-types)").unwrap();
    }
    if has_traits(program) {
        writeln!(output, "- [Χαρακτῆρες (Traits)](#χαρακτῆρες-traits)").unwrap();
    }
    if has_functions(program) {
        writeln!(
            output,
            "- [Λειτουργίαι (Functions)](#λειτουργίαι-functions)"
        )
        .unwrap();
    }
    if has_tests(program) {
        writeln!(output, "- [Δοκιμαί (Tests)](#δοκιμαί-tests)").unwrap();
    }
    writeln!(output).unwrap();

    // Types
    if has_types(program) {
        writeln!(output, "## Εἴδη (Types)").unwrap();
        for stmt in &program.statements {
            if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
                writeln!(output, "### {}", name).unwrap();
                writeln!(output, "| Πεδίον (Field) | Τύπος (Type) |").unwrap();
                writeln!(output, "|---|---|").unwrap();
                for (field_name, field_type) in fields {
                    writeln!(output, "| {} | {} |", field_name, field_type).unwrap();
                }
                writeln!(output).unwrap();
            }
        }
    }

    // Traits
    if has_traits(program) {
        writeln!(output, "## Χαρακτῆρες (Traits)").unwrap();
        for stmt in &program.statements {
            if let AnalyzedStatement::TraitDefinition { name, methods } = stmt {
                writeln!(output, "### {}", name).unwrap();
                for method in methods {
                    write!(output, "- **{}**(", method.name).unwrap();
                    for (i, (param_name, param_type)) in method.params.iter().enumerate() {
                        if i > 0 {
                            write!(output, ", ").unwrap();
                        }
                        write!(output, "{}: {}", param_name, param_type).unwrap();
                    }
                    write!(output, ")").unwrap();
                    if let Some(ret) = &method.return_type {
                        write!(output, " -> {}", ret).unwrap();
                    }
                    writeln!(output).unwrap();
                }
                writeln!(output).unwrap();
            }
        }
    }

    // Functions
    if has_functions(program) {
        writeln!(output, "## Λειτουργίαι (Functions)").unwrap();
        for stmt in &program.statements {
            if let AnalyzedStatement::FunctionDef {
                name,
                params,
                return_type,
                ..
            } = stmt
            {
                writeln!(output, "### {}", name).unwrap();
                write!(output, "**{}**(", name).unwrap();
                for (i, (param_name, param_type)) in params.iter().enumerate() {
                    if i > 0 {
                        write!(output, ", ").unwrap();
                    }
                    let type_str = param_type
                        .as_ref()
                        .map(|t| t.to_string())
                        .unwrap_or_else(|| "Ἄγνωστον".to_string());
                    write!(output, "{}: {}", param_name, type_str).unwrap();
                }
                write!(output, ")").unwrap();
                if let Some(ret) = return_type {
                    write!(output, " -> {}", ret).unwrap();
                }
                writeln!(output).unwrap();
                writeln!(output).unwrap();
            }
        }
    }

    // Tests
    if has_tests(program) {
        writeln!(output, "## Δοκιμαί (Tests)").unwrap();
        for stmt in &program.statements {
            if let AnalyzedStatement::TestDeclaration { name, .. } = stmt {
                writeln!(output, "- {}", name).unwrap();
            }
        }
    }

    output
}

fn has_types(program: &AnalyzedProgram) -> bool {
    program
        .statements
        .iter()
        .any(|s| matches!(s, AnalyzedStatement::TypeDefinition { .. }))
}

fn has_traits(program: &AnalyzedProgram) -> bool {
    program
        .statements
        .iter()
        .any(|s| matches!(s, AnalyzedStatement::TraitDefinition { .. }))
}

fn has_functions(program: &AnalyzedProgram) -> bool {
    program
        .statements
        .iter()
        .any(|s| matches!(s, AnalyzedStatement::FunctionDef { .. }))
}

fn has_tests(program: &AnalyzedProgram) -> bool {
    program
        .statements
        .iter()
        .any(|s| matches!(s, AnalyzedStatement::TestDeclaration { .. }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;
    use crate::semantic::analyze_program;

    #[test]
    fn test_generate_docs_types() {
        let source = "εἶδος Χρήστης ὁρίζειν { ὄνομα Ὄνομα. ἡλικία Ἀριθμός. }.";
        let ast = parse(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();

        let docs = generate_docs(&analyzed, "user.gl");

        println!("{}", docs);

        assert!(docs.contains("# Βιβλιοθήκη (Library) - user.gl"));
        assert!(docs.contains("## Εἴδη (Types)"));
        // AnalyzedProgram uses normalized names (lowercase/no-diacritics)
        assert!(docs.contains("### χρηστης"));
        // Fields are also normalized
        assert!(docs.contains("| ονομα |"));
        assert!(docs.contains("| ηλικια |"));
    }

    #[test]
    fn test_generate_docs_traits() {
        let source = "χαρακτήρ Δεικτόν ὁρίζειν { δεῖ δεῖξαι. }.";
        let ast = parse(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();

        let docs = generate_docs(&analyzed, "trait.gl");

        println!("{}", docs);

        assert!(docs.contains("## Χαρακτῆρες (Traits)"));
        // AnalyzedProgram uses normalized names
        assert!(docs.contains("### δεικτον"));
        assert!(docs.contains("δειξαι"));
    }

    #[test]
    fn test_generate_docs_tests() {
        let source = "δοκιμή «test1». «ok» λέγε. τέλος.";
        let ast = parse(source).unwrap();
        let analyzed = analyze_program(&ast).unwrap();

        let docs = generate_docs(&analyzed, "test.gl");

        println!("{}", docs);

        assert!(docs.contains("## Δοκιμαί (Tests)"));
        assert!(docs.contains("- test1"));
    }
}
