//! The Diplomat (ὁ Πρέσβυς) - TypeScript Declaration Generator
//!
//! This module implements the "Diplomat" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript Interfaces.
//!
//! # Purpose
//!
//! A Diplomat translates between cultures. This tool bridges the ancient world
//! of ΓΛΩΣΣΑ with the modern frontend world by automatically generating TypeScript
//! `.d.ts` type declarations directly from your ΓΛΩΣΣΑ structures.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Diplomat tool to generate TypeScript interfaces from Glossa types.
///
/// The Diplomat (Πρέσβυς) tool reads the provided source file, compiles it, and automatically
/// generates corresponding TypeScript interface definitions for any type definitions found.
///
/// # Examples
///
/// ```rust,no_run
/// use glossa::experimental::diplomat::run_diplomat;
/// use std::path::Path;
///
/// let input = Path::new("schema.γλ");
/// if let Err(e) = run_diplomat(&input) {
///     eprintln!("Interface generation failed: {}", e);
/// }
/// ```
pub fn run_diplomat(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πρέσβυς (Generating TypeScript Interfaces)", "🤝");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Diplomat\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);

                // If it's an Option type, make it an optional property in TS
                let is_opt = matches!(field_type, GlossaType::Option(_));
                let opt_char = if is_opt { "?" } else { "" };

                let display_type = if is_opt {
                    if let GlossaType::Option(inner) = field_type {
                        glossa_type_to_ts(inner)
                    } else {
                        ts_type
                    }
                } else {
                    ts_type
                };

                let _ = writeln!(output, "    {}{}: {};", field_name, opt_char, display_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   D I P L O M A T".bold().magenta());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript")
            .add_attribute(Attribute::Bold)
            .fg(Color::Magenta),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, _err) => glossa_type_to_ts(ok),
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use smol_str::SmolStr;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: SmolStr::new("χρηστης"),
                gender: crate::morphology::Gender::Masculine,
                fields: vec![]
            }),
            "χρηστης"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
