//! The Ambassador (ὁ Πρέσβυς) - TypeScript Declaration Generator
//!
//! This module implements the "Ambassador" tool, which acts as a diplomat between
//! ΓΛΩΣΣΑ and the JavaScript ecosystem by generating TypeScript declaration files (`.d.ts`).
//!
//! # Purpose
//!
//! In the modern web era, TypeScript is the lingua franca of frontend and backend integration.
//! The Ambassador translates ΓΛΩΣΣΑ type definitions (`εἶδος`) and function signatures (`ἔργον`)
//! into TypeScript interfaces and function declarations, allowing seamless integration.
//!
//! # How it Works
//!
//! 1. Parses and semantically analyzes the source `.γλ` code.
//! 2. Scans the `AnalyzedProgram` for `TypeDefinition` and function definitions.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to TypeScript types (`number`, `string`, etc.).
//! 4. Outputs a formatted `.d.ts` file alongside the source file.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Ambassador tool to generate TypeScript declarations from Glossa code.
///
/// The Ambassador (ὁ Πρέσβυς) tool reads the provided source file, compiles it,
/// and automatically generates a corresponding TypeScript `.d.ts` file for any
/// struct or function definitions found.
///
/// # Examples
///
/// ```rust,no_run
/// use glossa::tools::ambassador::run_ambassador;
/// use std::path::Path;
///
/// let input = Path::new("module.γλ");
/// if let Err(e) = run_ambassador(&input) {
///     eprintln!("Declaration generation failed: {}", e);
/// }
/// ```
pub fn run_ambassador(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πρέσβυς (Generating TypeScript Declarations)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Ambassador\n");
    output.push_str("// TypeScript Declarations\n\n");

    // Output types (structs)
    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                let _ = writeln!(output, "    {}: {};", field_name, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    // Output functions
    for func in program.scope.functions() {
        let _ = write!(output, "export declare function {}(", func.name);
        for (i, t) in func.param_types.iter().enumerate() {
            if i > 0 {
                let _ = write!(output, ", ");
            }
            let ts_type = glossa_type_to_ts(t);
            let _ = write!(output, "arg_{}: {}", i, ts_type);
        }
        let _ = write!(output, "): ");
        if let Some(ret_type) = &func.return_type {
            let _ = write!(output, "{};", glossa_type_to_ts(ret_type));
        } else {
            let _ = write!(output, "void;");
        }
        let _ = writeln!(output, "\n");
    }

    let output_path = input.with_extension("d.ts");
    if let Err(e) = std::fs::write(&output_path, &output) {
        return Err(miette::miette!(
            "Failed to write typescript declaration file: {}",
            e
        ));
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   A M B A S S A D O R".bold().cyan());
    println!("   {}", "TypeScript Declarations".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript (.d.ts)")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();
    println!(
        "   {} {}",
        "Saved to:".bold(),
        output_path.display().to_string().cyan()
    );
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => format!("Map<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v)),
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => {
            format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { params, returns } => {
            let params_str = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg_{}: {}", i, glossa_type_to_ts(p)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({}) => {}", params_str, glossa_type_to_ts(returns))
        }
        GlossaType::Unit => "void".to_string(),
        GlossaType::Unknown => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Map<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number | string"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: Gender::Masculine,
                fields: vec![]
            }),
            "User"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function {
                params: vec![GlossaType::Number, GlossaType::String],
                returns: Box::new(GlossaType::Boolean)
            }),
            "(arg_0: number, arg_1: string) => boolean"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }

    #[test]
    fn test_run_ambassador_success() {
        use std::fs;
        use tempfile::tempdir;

        let dir = tempdir().unwrap();
        let input_path = dir.path().join("api.γλ");
        fs::write(&input_path, "εἶδος Χρήστης ὁρίζειν { ὄνομα ὀνόματος. }.\nπροσθεσις ὁρίζειν τῷ ξ ἀριθμοῦ τῷ ψ ἀριθμοῦ· δός ξ ψ ἄθροισμα.").unwrap();

        let result = run_ambassador(&input_path);
        assert!(result.is_ok());

        let output_path = input_path.with_extension("d.ts");
        assert!(output_path.exists());

        let ts = fs::read_to_string(&output_path).unwrap();
        assert!(ts.contains("export interface χρηστης {"));
        assert!(ts.contains("ονομα: string;"));
        assert!(
            ts.contains("export declare function προσθεσις(arg_0: number, arg_1: number): number;")
        );
    }

    #[test]
    fn test_run_ambassador_file_error() {
        use std::fs;
        use tempfile::tempdir;

        let dir = tempdir().unwrap();
        let input_path = dir.path().join("api.γλ");
        fs::write(&input_path, "εἶδος Χρήστης ὁρίζειν { }.").unwrap();

        let output_path = input_path.with_extension("d.ts");
        fs::create_dir(&output_path).unwrap();

        let result = run_ambassador(&input_path);
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(
            err_msg.contains("Failed to write")
                || err_msg.contains("directory")
                || err_msg.contains("denied")
                || err_msg.contains("Permission")
        );
    }
}
