//! The Ambassador (ὁ Πρέσβυς) - TypeScript Declaration Exporter
//!
//! This module implements an experimental tool that converts ΓΛΩΣΣΑ type definitions
//! and traits into TypeScript Declaration (`.d.ts`) files.
//!
//! # Purpose
//!
//! The Ambassador bridges the ancient back-end with the modern front-end. By
//! transpiling Glossa structures to TypeScript interfaces, we can use ΓΛΩΣΣΑ
//! as a domain modeling language that seamlessly integrates with web applications.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Run the Ambassador tool on a file
pub fn run_ambassador(input: &Path, output_path: Option<&Path>) -> Result<()> {
    let source = load_source(input)?;
    let status = Status::start_with_symbol("Πρεσβεία (Transpiling to TypeScript)", "📜");

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα (Error)");
            return Err(e);
        }
    };

    let mut ts_code = String::new();
    writeln!(ts_code, "// Generated by ΓΛΩΣΣΑ Ambassador (ὁ Πρέσβυς)").unwrap();
    writeln!(ts_code, "// Do not edit manually\n").unwrap();

    let mut generated_any = false;

    for stmt in &program.statements {
        match stmt {
            AnalyzedStatement::TypeDefinition { name, fields } => {
                generated_any = true;
                writeln!(ts_code, "export interface {} {{", name).unwrap();
                for (field_name, field_type) in fields {
                    let ts_type = glossa_type_to_ts(field_type);
                    writeln!(ts_code, "    {}: {};", field_name, ts_type).unwrap();
                }
                writeln!(ts_code, "}}\n").unwrap();
            }
            AnalyzedStatement::TraitDefinition { name, methods } => {
                generated_any = true;
                writeln!(ts_code, "export interface {} {{", name).unwrap();
                for method in methods {
                    let mut params = Vec::new();
                    for (p_name, p_type) in &method.params {
                        params.push(format!("{}: {}", p_name, glossa_type_to_ts(p_type)));
                    }
                    let ret_type = method
                        .return_type
                        .as_ref()
                        .map(glossa_type_to_ts)
                        .unwrap_or_else(|| "void".to_string());

                    writeln!(
                        ts_code,
                        "    {}({}): {};",
                        method.name,
                        params.join(", "),
                        ret_type
                    )
                    .unwrap();
                }
                writeln!(ts_code, "}}\n").unwrap();
            }
            _ => {}
        }
    }

    status.success();

    if !generated_any {
        println!("No types or traits found to export.");
        return Ok(());
    }

    if let Some(out) = output_path {
        std::fs::write(out, ts_code)
            .map_err(|e| miette::miette!("Failed to write output: {}", e))?;
        println!("TypeScript definitions exported to {}", out.display());
    } else {
        println!("{}", ts_code);
    }

    Ok(())
}

fn glossa_type_to_ts(t: &GlossaType) -> String {
    match t {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => format!("Map<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v)),
        GlossaType::Option(inner) => format!("{} | undefined", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => {
            format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Unit => "void".to_string(),
        GlossaType::Unknown => "any".to_string(),
        GlossaType::Function { params, returns } => {
            let mut p = Vec::new();
            for (i, param) in params.iter().enumerate() {
                p.push(format!("p{}: {}", i, glossa_type_to_ts(param)));
            }
            format!("({}) => {}", p.join(", "), glossa_type_to_ts(returns))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: crate::morphology::Gender::Masculine,
                fields: vec![]
            }),
            "User"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::String))),
            "string | undefined"
        );
    }
}
