//! The Architect (ὁ Ἀρχιτέκτων) - TypeScript Interface Generator
//!
//! This module implements the "Architect" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface` definitions.
//!
//! # Purpose
//!
//! Connecting the ancient backend to the modern web. The Architect translates
//! Glossa data structures into TypeScript, allowing seamless integration with
//! modern frontend frameworks.
//!
//! # How it Works
//!
//! The [`run_architect`] function:
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to TypeScript types (`number`, `string`, etc.).
//! 4. Outputs formatted TypeScript code to the terminal.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Architect tool to generate TypeScript interfaces from Glossa types.
pub fn run_architect(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἀρχιτέκτων (Generating TypeScript)", "🏛️");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Architect\n\n");

    let mut has_types = false;

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            has_types = true;
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                // Assume all fields are required for now unless they are Option.
                // If it's an Option, we can make it optional in TS.
                let optional_mark = if matches!(field_type, GlossaType::Option(_)) {
                    "?"
                } else {
                    ""
                };

                let _ = writeln!(output, "    {}{}: {};", field_name, optional_mark, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    if !has_types {
        output.push_str("// No type definitions found in the source file.\n");
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   A R C H I T E C T".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Definitions")
            .add_attribute(Attribute::Bold)
            .fg(Color::Blue),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(key, val) => format!(
            "Record<{}, {}>",
            glossa_type_to_ts(key),
            glossa_type_to_ts(val)
        ),
        GlossaType::Option(inner) => glossa_type_to_ts(inner),
        GlossaType::Function { .. } => "(...args: any[]) => any".to_string(),
        GlossaType::Unit => "void".to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number" // Made optional with `?` in formatting
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
    }

    #[test]
    fn test_run_architect_file_not_found() {
        let path = Path::new("non_existent_file.γλ");
        let result = run_architect(path);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("οὐχ εὑρέθη"));
    }
}
