use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use miette::Result;
use std::path::Path;

/// Run the Architect tool on a file
///
/// Reads the source file, compiles it, and generates GraphQL type and interface schemas.
pub fn run_architect(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἀρχιτέκτων (Generating GraphQL Schema)", "📐");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("# Auto-generated by ΓΛΩΣΣΑ Architect\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            output.push_str(&format!("type {} {{\n", name));
            for (field_name, field_type) in fields.iter() {
                let graphql_type = glossa_type_to_graphql(field_type);
                output.push_str(&format!("  {}: {}\n", field_name, graphql_type));
            }
            output.push_str("}\n\n");
        } else if let AnalyzedStatement::TraitDefinition { name, methods } = stmt {
            output.push_str(&format!("interface {} {{\n", name));
            for method in methods.iter() {
                let args_str = if method.params.is_empty() {
                    "".to_string()
                } else {
                    let mut args = Vec::new();
                    for (param_name, param_type) in &method.params {
                        args.push(format!(
                            "{}: {}",
                            param_name,
                            glossa_type_to_graphql(param_type)
                        ));
                    }
                    format!("({})", args.join(", "))
                };

                let return_str = match &method.return_type {
                    Some(ty) => glossa_type_to_graphql(ty),
                    None => "String".to_string(), // GraphQL doesn't have a real Unit type, String is a common placeholder or we could use a custom scalar, but standard types are safer. Let's use Boolean for a generic 'success' or just String. Let's use Boolean as it's small. Wait, standard GraphQL operations usually return an object or primitive. Let's use Boolean.
                };

                output.push_str(&format!("  {}{}: {}\n", method.name, args_str, return_str));
            }
            output.push_str("}\n\n");
        }
    }

    println!("{}", output);

    Ok(())
}

fn glossa_type_to_graphql(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "Int!".to_string(), // In GraphQL, standard Int is 32-bit, but there's no 64-bit standard scalar. Often people use Float or custom scalar for BigInt. Let's stick to Int! as it's built-in.
        GlossaType::String => "String!".to_string(),
        GlossaType::Boolean => "Boolean!".to_string(),
        GlossaType::List(inner) => format!("[{}]!", glossa_type_to_graphql(inner).replace("!", "")), // Usually [Type!]! or [Type]!. We'll do [Type]!
        GlossaType::Set(inner) => format!("[{}]!", glossa_type_to_graphql(inner).replace("!", "")),
        GlossaType::Map(_, _) => "JSON!".to_string(), // GraphQL doesn't have native maps, custom scalar JSON is typical.
        GlossaType::Option(inner) => {
            // Remove the ! for nullable types
            let inner_graphql = glossa_type_to_graphql(inner);
            inner_graphql.replace("!", "")
        }
        _ => "JSON!".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_graphql() {
        assert_eq!(glossa_type_to_graphql(&GlossaType::Number), "Int!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::String), "String!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::Boolean), "Boolean!");
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::List(Box::new(GlossaType::Number))),
            "[Int]!"
        );
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::Set(Box::new(GlossaType::Number))),
            "[Int]!"
        );
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "JSON!"
        );
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::Option(Box::new(GlossaType::Number))),
            "Int"
        );
        assert_eq!(glossa_type_to_graphql(&GlossaType::Unknown), "JSON!");
    }
}
