//! The Artisan (ὁ Τεχνίτης) - HTML Form Generator
//!
//! This module implements the "Artisan" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into HTML `<form>` markup.
//!
//! # Purpose
//!
//! The Artisan allows developers to quickly generate web interfaces for their
//! data structures, mapping internal types to appropriate HTML input fields.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Artisan tool to generate HTML forms from Glossa types.
///
/// The Artisan (Τεχνίτης) reads the provided source file, compiles it, and automatically
/// generates corresponding HTML `<form>` markup for any type definitions found.
pub fn run_artisan(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Τεχνίτης (Generating HTML Forms)", "🎨");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("<!-- Auto-generated by ΓΛΩΣΣΑ Artisan -->\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "<form id=\"form_{}\">", name);
            let _ = writeln!(output, "  <fieldset>");
            let _ = writeln!(output, "    <legend>{}</legend>", name);

            for (field_name, field_type) in fields.iter() {
                let input_tag = glossa_type_to_html_input(field_type, field_name);
                let _ = writeln!(output, "    <div>");
                let _ = writeln!(
                    output,
                    "      <label for=\"{}\">{}</label>",
                    field_name, field_name
                );
                let _ = writeln!(output, "      {}", input_tag);
                let _ = writeln!(output, "    </div>");
            }

            let _ = writeln!(output, "    <button type=\"submit\">Submit</button>");
            let _ = writeln!(output, "  </fieldset>");
            let _ = writeln!(output, "</form>\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   A R T I S A N".bold().cyan());
    println!("   {}", "HTML Form Markup".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("HTML Markup")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```html\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_html_input(g_type: &GlossaType, name: &str) -> String {
    match g_type {
        GlossaType::Number => format!("<input type=\"number\" id=\"{}\" name=\"{}\">", name, name),
        GlossaType::Boolean => format!(
            "<input type=\"checkbox\" id=\"{}\" name=\"{}\">",
            name, name
        ),
        GlossaType::String => format!("<input type=\"text\" id=\"{}\" name=\"{}\">", name, name),
        GlossaType::Option(inner) => glossa_type_to_html_input(inner, name),
        _ => format!("<input type=\"text\" id=\"{}\" name=\"{}\">", name, name),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_html_number() {
        assert_eq!(
            glossa_type_to_html_input(&GlossaType::Number, "age"),
            "<input type=\"number\" id=\"age\" name=\"age\">"
        );
    }

    #[test]
    fn test_glossa_type_to_html_boolean() {
        assert_eq!(
            glossa_type_to_html_input(&GlossaType::Boolean, "is_active"),
            "<input type=\"checkbox\" id=\"is_active\" name=\"is_active\">"
        );
    }

    #[test]
    fn test_glossa_type_to_html_string() {
        assert_eq!(
            glossa_type_to_html_input(&GlossaType::String, "username"),
            "<input type=\"text\" id=\"username\" name=\"username\">"
        );
    }

    #[test]
    fn test_glossa_type_to_html_fallback() {
        assert_eq!(
            glossa_type_to_html_input(&GlossaType::Unknown, "data"),
            "<input type=\"text\" id=\"data\" name=\"data\">"
        );
    }
}
