//! The Commander (ὁ Στρατηγός) - Bash Script Generator
//!
//! This module implements the "Commander" tool, which transpiles ΓΛΩΣΣΑ
//! programs into Bash scripts.

use crate::semantic::{AnalyzedExpr, AnalyzedExprKind, AnalyzedStatement};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Commander tool to generate Bash scripts from Glossa programs.
pub fn run_commander(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Στρατηγός (Generating Bash Script)", "🐚");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("#!/bin/bash\n");
    output.push_str("# Auto-generated by ΓΛΩΣΣΑ Commander\n\n");

    for stmt in &program.statements {
        transpile_statement(stmt, 0, &mut output);
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   C O M M A N D E R".bold().cyan());
    println!("   {}", "Bash Script".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);
    table.set_header(vec![
        Cell::new("Bash Script")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);
    let formatted_code = format!("```bash\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);
    println!("{table}");
    println!();

    Ok(())
}

fn transpile_statement(stmt: &AnalyzedStatement, indent: usize, out: &mut String) {
    let prefix = "    ".repeat(indent);
    match stmt {
        AnalyzedStatement::Binding { name, value, .. } => {
            let val = transpile_expr(value);
            let _ = writeln!(out, "{}{}={}", prefix, name, val);
        }
        AnalyzedStatement::Assignment { name, value } => {
            let val = transpile_expr(value);
            let _ = writeln!(out, "{}{}={}", prefix, name, val);
        }
        AnalyzedStatement::Print(exprs) => {
            let _ = write!(out, "{}echo ", prefix);
            for (i, expr) in exprs.iter().enumerate() {
                if i > 0 {
                    out.push(' ');
                }
                out.push_str(&transpile_expr(expr));
            }
            out.push('\n');
        }
        AnalyzedStatement::Expression(exprs) | AnalyzedStatement::Query(exprs) => {
            let _ = write!(out, "{}", prefix);
            for (i, expr) in exprs.iter().enumerate() {
                if i > 0 {
                    out.push(' ');
                }
                out.push_str(&transpile_expr(expr));
            }
            out.push('\n');
        }
        AnalyzedStatement::If {
            condition,
            then_body,
            else_body,
        } => {
            let cond = transpile_expr(condition);
            let _ = writeln!(out, "{}if [ {} ]; then", prefix, cond);
            for b in then_body {
                transpile_statement(b, indent + 1, out);
            }
            if let Some(eb) = else_body {
                let _ = writeln!(out, "{}else", prefix);
                for b in eb {
                    transpile_statement(b, indent + 1, out);
                }
            }
            let _ = writeln!(out, "{}fi", prefix);
        }
        AnalyzedStatement::While { condition, body } => {
            let cond = transpile_expr(condition);
            let _ = writeln!(out, "{}while [ {} ]; do", prefix, cond);
            for b in body {
                transpile_statement(b, indent + 1, out);
            }
            let _ = writeln!(out, "{}done", prefix);
        }
        AnalyzedStatement::For {
            variable,
            iterator,
            body,
        } => {
            let iter = transpile_expr(iterator);
            let _ = writeln!(out, "{}for {} in {}; do", prefix, variable, iter);
            for b in body {
                transpile_statement(b, indent + 1, out);
            }
            let _ = writeln!(out, "{}done", prefix);
        }
        AnalyzedStatement::Break => {
            let _ = writeln!(out, "{}break", prefix);
        }
        AnalyzedStatement::Continue => {
            let _ = writeln!(out, "{}continue", prefix);
        }
        AnalyzedStatement::Return { value } => {
            if let Some(v) = value {
                let val = transpile_expr(v);
                let _ = writeln!(out, "{}return {}", prefix, val);
            } else {
                let _ = writeln!(out, "{}return", prefix);
            }
        }
        AnalyzedStatement::FunctionDef { name, body, .. } => {
            let _ = writeln!(out, "{}function {} {{", prefix, name);
            for b in body {
                transpile_statement(b, indent + 1, out);
            }
            let _ = writeln!(out, "{}}}", prefix);
        }
        AnalyzedStatement::Match { .. }
        | AnalyzedStatement::TypeDefinition { .. }
        | AnalyzedStatement::TraitDefinition { .. }
        | AnalyzedStatement::TraitImplementation { .. }
        | AnalyzedStatement::TestDeclaration { .. } => {
            let _ = writeln!(out, "{}# Unsupported statement mapped to bash", prefix);
        }
    }
}

fn transpile_expr(expr: &AnalyzedExpr) -> String {
    match &expr.expr {
        AnalyzedExprKind::StringLiteral(s) => format!("\"{}\"", s),
        AnalyzedExprKind::NumberLiteral(n) => format!("{}", n),
        AnalyzedExprKind::BooleanLiteral(b) => {
            if *b {
                "true".to_string()
            } else {
                "false".to_string()
            }
        }
        AnalyzedExprKind::Variable(v) => format!("${v}"),
        AnalyzedExprKind::PropertyAccess { owner, property } => {
            format!("{}.{}", transpile_expr(owner), property)
        }
        AnalyzedExprKind::VerbCall { verb, args }
        | AnalyzedExprKind::FunctionCall { func: verb, args } => {
            let mut s = verb.to_string();
            for a in args {
                s.push_str(&format!(" {}", transpile_expr(a)));
            }
            format!("$({})", s)
        }
        AnalyzedExprKind::BinOp { left, op: _, right } => {
            format!("$(({} + {}))", transpile_expr(left), transpile_expr(right))
        }
        AnalyzedExprKind::UnaryOp { op: _, operand } => {
            format!("!{}", transpile_expr(operand))
        }
        AnalyzedExprKind::Range { .. }
        | AnalyzedExprKind::ArrayLiteral(_)
        | AnalyzedExprKind::Some(_)
        | AnalyzedExprKind::None
        | AnalyzedExprKind::Ok(_)
        | AnalyzedExprKind::Err(_)
        | AnalyzedExprKind::Unwrap(_)
        | AnalyzedExprKind::Try(_)
        | AnalyzedExprKind::IndexAccess { .. }
        | AnalyzedExprKind::MethodCall { .. }
        | AnalyzedExprKind::StructInstantiation { .. }
        | AnalyzedExprKind::Lambda { .. }
        | AnalyzedExprKind::CollectionNew { .. }
        | AnalyzedExprKind::Assert { .. }
        | AnalyzedExprKind::AssertEq { .. } => "\"unsupported_expr\"".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_commander_basic() {
        let stmt = AnalyzedStatement::Binding {
            name: "x".into(),
            value: AnalyzedExpr {
                expr: AnalyzedExprKind::NumberLiteral(42),
                glossa_type: crate::semantic::GlossaType::Number,
            },
            mutable: false,
        };
        let mut out = String::new();
        transpile_statement(&stmt, 0, &mut out);
        assert_eq!(out, "x=42\n");
    }
}
