use crate::semantic::GlossaType;

pub fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => format!(
            "Result<{}, {}>",
            glossa_type_to_ts(ok),
            glossa_type_to_ts(err)
        ), // Assuming a Result type is defined, or generic representation
        GlossaType::Unit => "void".to_string(),
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { params, returns } => {
            let param_strs: Vec<String> = params.iter().map(glossa_type_to_ts).collect();
            format!(
                "(...args: [{}]) => {}",
                param_strs.join(", "),
                glossa_type_to_ts(returns)
            )
        }
        GlossaType::Unknown => "any".to_string(),
    }
}

use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Diplomat tool to generate TypeScript type declarations (`.d.ts`) from Glossa code.
pub fn run_diplomat(input: &Path) -> Result<()> {
    let source = load_source(input)?;
    let status = Status::start_with_symbol("Διπλωμάτης (Generating TS Declarations)", "📜");

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα (Error)");
            return Err(e);
        }
    };

    let mut ts = String::with_capacity(4096);
    let filename = input.file_name().unwrap_or_default().to_string_lossy();

    writeln!(
        ts,
        "// Auto-generated by ΓΛΩΣΣΑ Diplomat for `{}`\n",
        filename
    )
    .unwrap();

    // Polyfill for Result if it doesn't exist natively in TS.
    writeln!(
        ts,
        "export type Result<T, E> = {{ ok: true; value: T }} | {{ ok: false; error: E }};\n"
    )
    .unwrap();

    // Export Types (Structs)
    let mut types = program.scope.types().peekable();
    if types.peek().is_some() {
        for (name, type_def) in types {
            if let GlossaType::Struct { fields, .. } = type_def {
                writeln!(ts, "export interface {} {{", name).unwrap();
                for (field_name, field_type) in fields {
                    writeln!(ts, "    {}: {};", field_name, glossa_type_to_ts(field_type)).unwrap();
                }
                writeln!(ts, "}}\n").unwrap();
            }
        }
    }

    // Export Traits (Interfaces)
    let mut traits = program.scope.traits().peekable();
    if traits.peek().is_some() {
        for (name, trait_def) in traits {
            writeln!(ts, "export interface {} {{", name).unwrap();
            for method in &trait_def.methods {
                let params = method
                    .params
                    .iter()
                    .map(|(_, t)| glossa_type_to_ts(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret =
                    glossa_type_to_ts(method.return_type.as_ref().unwrap_or(&GlossaType::Unit));
                writeln!(ts, "    {}(...args: [{}]): {};", method.name, params, ret).unwrap();
            }
            writeln!(ts, "}}\n").unwrap();
        }
    }

    // Export Functions (Verbs)
    let mut functions = program.scope.functions().peekable();
    if functions.peek().is_some() {
        for func in functions {
            let params = func
                .param_types
                .iter()
                .map(glossa_type_to_ts)
                .collect::<Vec<_>>()
                .join(", ");
            let ret = glossa_type_to_ts(func.return_type.as_ref().unwrap_or(&GlossaType::Unit));
            writeln!(
                ts,
                "export declare function {}(...args: [{}]): {};",
                func.name, params, ret
            )
            .unwrap();
        }
    }

    let output_path = input.with_extension("d.ts");
    if let Err(e) = std::fs::write(&output_path, &ts) {
        status.error("Σφάλμα ἀρχείου (File Error)");
        return Err(miette::miette!("Failed to write declaration file: {}", e));
    }

    status.success();

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   D I P L O M A T".bold().cyan());
    println!("   {}", "TypeScript Declarations Generated".italic().dim());
    println!();
    println!(
        "   {} {}",
        "Saved to:".bold(),
        output_path.display().to_string().cyan()
    );
    println!();

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "Result<number, string>"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: Gender::Neuter,
                fields: vec![]
            }),
            "User"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function {
                params: vec![GlossaType::Number],
                returns: Box::new(GlossaType::String)
            }),
            "(...args: [number]) => string"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }

    #[test]
    fn test_run_diplomat_success() {
        let dir = tempdir().unwrap();
        let input_path = dir.path().join("api.γλ");
        fs::write(&input_path, "εἶδος Χρήστης ὁρίζειν { ὄνομα ὀνόματος. }.").unwrap();

        let result = run_diplomat(&input_path);
        assert!(result.is_ok());

        let output_path = input_path.with_extension("d.ts");
        assert!(output_path.exists());

        let ts = fs::read_to_string(&output_path).unwrap();
        assert!(ts.contains("export interface χρηστης"));
        assert!(ts.contains("ονομα: string;"));
    }

    #[test]
    fn test_run_diplomat_with_functions() {
        let dir = tempdir().unwrap();
        let input_path = dir.path().join("api.γλ");
        let source = "
        πρόσθεσις ὁρίζειν τῷ ξ ἀριθμοῦ τῷ ψ ἀριθμοῦ· δός ξ ψ ἄθροισμα.
        ";
        fs::write(&input_path, source).unwrap();

        let result = run_diplomat(&input_path);
        assert!(result.is_ok());

        let output_path = input_path.with_extension("d.ts");
        assert!(output_path.exists());

        let ts = fs::read_to_string(&output_path).unwrap();
        assert!(
            ts.contains("export declare function προσθεσις(...args: [number, number]): number;")
        );
    }
}
