//! The Diplomat (ὁ Διπλωμάτης) - TypeScript Interface Generator
//!
//! This module implements the "Diplomat" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface` definitions.
//!
//! # Purpose
//!
//! A diplomat bridges the gap between different cultures. This tool bridges
//! the gap between the Ancient Greek backend semantics of Glossa and the modern
//! frontend world of TypeScript.
use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Diplomat tool to generate TypeScript interfaces from Glossa types.
pub fn run_diplomat(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    println!(
        "{} {}",
        "⚡".yellow(),
        "Διπλωμάτης (Generating TypeScript)...".bold()
    );

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("{} {}", "✕".red(), "Σφάλμα ἀρχείου (File Error)".bold());
            return Err(e);
        }
    };

    // Need to use parser then analyze_program because analyze_source isn't public
    let ast = match crate::parser::parse(&source) {
        Ok(a) => a,
        Err(e) => {
            eprintln!("{} {}", "✕".red(), "Σφάλμα συντάξεως (Parse Error)".bold());
            return Err(miette::miette!("{}", e));
        }
    };

    let program = match crate::semantic::analyze_program(&ast) {
        Ok(p) => p,
        Err(e) => {
            eprintln!(
                "{} {}",
                "✕".red(),
                "Σφάλμα ἀναλύσεως (Analysis Error)".bold()
            );
            return Err(miette::miette!("{}", e));
        }
    };

    println!(
        "{} {}",
        "✓".green(),
        "Διπλωμάτης (Generating TypeScript) (0.01s)".bold()
    );

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Diplomat\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                let _ = writeln!(output, "    {}: {};", field_name, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   D I P L O M A T".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);
    table.set_header(vec![
        Cell::new("TypeScript Interfaces")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);
    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);
    println!("{table}");
    println!();
    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) | GlossaType::Set(inner) => {
            format!("{}[]", glossa_type_to_ts(inner))
        }
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => {
            format!("{} | null", glossa_type_to_ts(inner))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic::GlossaType;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "string[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
