//! The Eidolon (τὸ Εἴδωλον) - GraphQL Schema Generator
//!
//! This module implements the "Eidolon" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into GraphQL schema definitions.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Eidolon tool to generate GraphQL schemas from Glossa types.
pub fn run_eidolon(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Εἴδωλον (Generating GraphQL Schema)", "✨");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("# Auto-generated by ΓΛΩΣΣΑ Eidolon\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "type {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let gql_type = glossa_type_to_graphql(field_type);
                let _ = writeln!(output, "  {}: {}", field_name, gql_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   E I D O L O N".bold().cyan());
    println!("   {}", "GraphQL Schema".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("GraphQL Schema")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```graphql\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_graphql(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "Int!".to_string(),
        GlossaType::String => "String!".to_string(),
        GlossaType::Boolean => "Boolean!".to_string(),
        GlossaType::List(inner) => format!("[{}]!", glossa_type_to_graphql(inner).replace("!", "")),
        GlossaType::Option(inner) => {
            let inner_gql = glossa_type_to_graphql(inner);
            inner_gql.replace("!", "")
        }
        _ => "JSON!".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_graphql() {
        assert_eq!(glossa_type_to_graphql(&GlossaType::Number), "Int!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::String), "String!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::Boolean), "Boolean!");
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::List(Box::new(GlossaType::Number))),
            "[Int]!"
        );
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::Option(Box::new(GlossaType::String))),
            "String"
        );
        assert_eq!(glossa_type_to_graphql(&GlossaType::Unknown), "JSON!");
    }
}
