//! The Emissary (ὁ Ἄγγελος) - TypeScript Exporter
//!
//! This module implements the "Emissary" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript interfaces
//! (`.d.ts`).
//!
//! # Purpose
//!
//! This tool bridges the gap between ancient Greek semantics and modern web APIs,
//! allowing seamless integration of ΓΛΩΣΣΑ as a backend data modeling language
//! for frontend web applications.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Emissary tool to generate TypeScript interfaces from Glossa types.
pub fn run_emissary(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἄγγελος (Generating TypeScript Interfaces)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Emissary\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                // In TypeScript, if the type is Optional, we could mark the field as optional too
                let is_optional = matches!(field_type, GlossaType::Option(_));
                let is_optional = matches!(field_type, GlossaType::Option(_));
                let opt_marker = if is_optional { "?" } else { "" };
                // If it's a top-level Optional, the ? handles undefined natively, so we strip the `| undefined` from ts_type to keep it clean.
                let mut display_type = ts_type;
                if is_optional {
                    if let GlossaType::Option(inner) = field_type {
                        display_type = glossa_type_to_ts(inner);
                    }
                }

                let _ = writeln!(output, "    {}{}: {};", field_name, opt_marker, display_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   E M I S S A R Y".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript (.d.ts)")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => format!("({} | undefined)", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => {
            format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Unit => "void".to_string(),
        GlossaType::Function { params, returns } => {
            let mut p = Vec::new();
            for (i, param) in params.iter().enumerate() {
                p.push(format!("p{}: {}", i, glossa_type_to_ts(param)));
            }
            format!("({}) => {}", p.join(", "), glossa_type_to_ts(returns))
        }
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "(number | undefined)"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Option(Box::new(GlossaType::String))))),
            "(string | undefined)[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number | string"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: Gender::Masculine,
                fields: vec![]
            }),
            "User"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function {
                params: vec![GlossaType::Number, GlossaType::String],
                returns: Box::new(GlossaType::Boolean)
            }),
            "(p0: number, p1: string) => boolean"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
