//! The Envoy (ὁ Ἄγγελος) - Protobuf Schema Generator
//!
//! This module implements the "Envoy" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into Protobuf messages.
//!

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Envoy tool to generate Protobuf schemas from Glossa types.
pub fn run_envoy(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἄγγελος (Generating Protobuf)", "🕊️");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Envoy\n");
    output.push_str("syntax = \"proto3\";\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "message {} {{", name);
            for (i, (field_name, field_type)) in fields.iter().enumerate() {
                let proto_type = glossa_type_to_proto(field_type);
                let _ = writeln!(output, "  {} {} = {};", proto_type, field_name, i + 1);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   E N V O Y".bold().cyan());
    println!("   {}", "Protobuf Schema".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("Protobuf Schema")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```proto\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_proto(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "int64".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "bool".to_string(),
        GlossaType::List(inner) | GlossaType::Set(inner) => {
            format!("repeated {}", glossa_type_to_proto(inner))
        }
        GlossaType::Map(k, v) => {
            format!(
                "map<{}, {}>",
                glossa_type_to_proto(k),
                glossa_type_to_proto(v)
            )
        }
        GlossaType::Option(inner) => {
            format!("optional {}", glossa_type_to_proto(inner))
        }
        _ => "Any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_proto() {
        assert_eq!(glossa_type_to_proto(&GlossaType::Number), "int64");
        assert_eq!(glossa_type_to_proto(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_proto(&GlossaType::Boolean), "bool");

        assert_eq!(
            glossa_type_to_proto(&GlossaType::List(Box::new(GlossaType::String))),
            "repeated string"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Set(Box::new(GlossaType::String))),
            "repeated string"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "map<string, int64>"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Option(Box::new(GlossaType::Number))),
            "optional int64"
        );
        assert_eq!(glossa_type_to_proto(&GlossaType::Unknown), "Any");
    }
}
