//! The Herald (ὁ Κῆρυξ) - TypeScript Interface Generator
//!
//! This module implements the "Herald" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface`
//! declarations.
//!
//! # Purpose
//!
//! A herald delivers messages across borders. This tool bridges the gap between a
//! ΓΛΩΣΣΑ backend and modern frontend ecosystems by automatically generating
//! TypeScript definitions, ensuring end-to-end type safety.
//!
//! # How it Works
//!
//! The [`run_herald`](crate::tools::herald::run_herald) function orchestrates the process:
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types to TypeScript types (`string`, `number`, `boolean`, etc.).
//! 4. Outputs formatted TypeScript code to the terminal.
use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Herald tool to generate TypeScript interfaces from Glossa types.
///
/// The Herald (Κῆρυξ) tool reads the provided source file, compiles it, and automatically
/// generates corresponding TypeScript `interface` declarations for any type definitions found.
///
/// # Errors
///
/// Returns a [`miette::Result`] if the file cannot be read, or if there is a parsing
/// or semantic analysis error during compilation.
pub fn run_herald(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Κῆρυξ (Generating TypeScript)", "📣");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Herald\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            // Convert to PascalCase for TS interface names if needed
            let interface_name = to_pascal_case(name);
            let _ = writeln!(output, "export interface {} {{", interface_name);
            for (field_name, field_type) in fields.iter() {
                // Convert to camelCase for TS properties
                let prop_name = to_camel_case(field_name);
                let ts_type = glossa_type_to_ts(field_type);

                // If it's an Option type, make the property optional in TS
                if matches!(field_type, GlossaType::Option(_)) {
                    let _ = writeln!(output, "    {}?: {};", prop_name, ts_type);
                } else {
                    let _ = writeln!(output, "    {}: {};", prop_name, ts_type);
                }
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   H E R A L D".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Output")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => glossa_type_to_ts(inner), // Optionality handled by '?:' in property
        GlossaType::Result(ok, err) => {
            format!("({} | {})", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => to_pascal_case(name),
        _ => "any".to_string(),
    }
}

// Simple helper to capitalize first letter (Greek-aware)
fn to_pascal_case(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

// Simple helper to lowercase first letter
fn to_camel_case(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        // Option is unwrapped because the `?` handles the undefined part
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "(number | string)"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }

    #[test]
    fn test_casing() {
        assert_eq!(to_pascal_case("χρήστης"), "Χρήστης");
        assert_eq!(to_camel_case("Ὄνομα"), "ὄνομα");
    }
}
