//! The Hermes (ὁ Ἑρμῆς) Tool - TypeScript Interface Generator
//!
//! This module implements the "Hermes" tool, acting as a messenger between
//! ΓΛΩΣΣΑ backend code and modern frontend technologies. It reads Glossa
//! `εἶδος` (Struct) definitions and transpiles them into TypeScript `interface`s.
//!
//! # Purpose
//!
//! Hermes facilitates seamless full-stack development by generating type-safe
//! TypeScript contracts directly from Glossa's semantic types. This ensures
//! that data moving across the wire matches the compiler's expected structures.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Hermes tool to generate TypeScript interfaces.
///
/// This command reads the source code, compiles it semantically, and translates
/// any structure definitions (`εἶδος`) into standard TypeScript interfaces.
pub fn run_hermes(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἑρμῆς (Generating TypeScript)", "🪽");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Hermes\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                // In TS, options/nullables are often handled via `?` operator on the field,
                // but since Glossa's Option explicitly means `T | null` or `T | undefined`,
                // we handle it here by checking if it's an Option to add `?`.
                let is_optional = matches!(field_type, GlossaType::Option(_));
                let opt_mark = if is_optional { "?" } else { "" };

                let _ = writeln!(output, "    {}{}: {};", field_name, opt_mark, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   H E R M E S".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Output")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => glossa_type_to_ts(inner), // the `?` mark on field handles optionality
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;
    use smol_str::SmolStr;

    #[test]
    fn test_glossa_type_to_ts_primitives() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }

    #[test]
    fn test_glossa_type_to_ts_collections() {
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::String))),
            "Set<string>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Boolean)
            )),
            "Record<string, boolean>"
        );
    }

    #[test]
    fn test_glossa_type_to_ts_structs_and_options() {
        let custom_struct = GlossaType::Struct {
            name: SmolStr::new("User"),
            gender: Gender::Masculine,
            fields: vec![],
        };
        assert_eq!(glossa_type_to_ts(&custom_struct), "User");

        // The field itself gets the `?`, so glossa_type_to_ts just returns the inner type
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
    }
}
