//! The Merchant (ὁ Ἔμπορος) - TypeScript Interface Generator
//!
//! This module implements the "Merchant" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript interfaces.

use crate::semantic::{AnalyzedStatement, GlossaType};
use miette::Result;
use std::fmt::Write;
use std::path::Path;

pub fn run_merchant(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    println!("🛒 Ἔμπορος (Generating TypeScript Interfaces)...");

    let source = match std::fs::read_to_string(input) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("Σφάλμα ἀρχείου (File Error): {}", e);
            return Err(miette::miette!("Failed to read file"));
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    println!("✅ Success!");

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Merchant\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                // Assume all fields are required for now
                let _ = writeln!(output, "  {}: {};", field_name, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   Γ Λ Ω Σ Σ Α   M E R C H A N T");
    println!("   TypeScript Interfaces");
    println!();

    println!("```typescript\n{}\n```", output.trim());
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, _err) => glossa_type_to_ts(ok),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number"
        );
    }
}
