//! The Messenger (ὁ Ἄγγελος) - Protobuf Schema Generator
//!
//! This module implements the "Messenger" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into Protocol Buffers `.proto` syntax.
//!
//! # Purpose
//!
//! Connecting ΓΛΩΣΣΑ structures to microservices. Protobuf is a cross-language
//! message format. This exporter allows data structures defined in Ancient Greek
//! semantics to be sent across the network.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Messenger tool to generate Protobuf definitions from Glossa types.
///
/// # Examples
///
/// ```rust,no_run
/// use glossa::tools::messenger::run_messenger;
/// use std::path::Path;
///
/// let input = Path::new("schema.γλ");
/// if let Err(e) = run_messenger(&input) {
///     eprintln!("Protobuf generation failed: {}", e);
/// }
/// ```
pub fn run_messenger(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Ἄγγελος (Generating Protobuf Schema)", "✉️");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Messenger\n");
    output.push_str("syntax = \"proto3\";\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "message {} {{", name);
            for (i, (field_name, field_type)) in fields.iter().enumerate() {
                let proto_type = glossa_type_to_proto(field_type);
                // In proto3, fields have unique numbers starting from 1
                let field_number = i + 1;

                // If the type is Option, we add the `optional` keyword for proto3
                let prefix = if matches!(field_type, GlossaType::Option(_)) {
                    "optional "
                } else {
                    ""
                };

                let _ = writeln!(
                    output,
                    "    {}{} {} = {};",
                    prefix, proto_type, field_name, field_number
                );
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   M E S S E N G E R".bold().magenta());
    println!("   {}", "Protobuf Schema".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("Protobuf Definition")
            .add_attribute(Attribute::Bold)
            .fg(Color::Magenta),
    ]);

    let formatted_code = format!("```protobuf\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_proto(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "int64".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "bool".to_string(),
        GlossaType::List(inner) => format!("repeated {}", glossa_type_to_proto(inner)),
        GlossaType::Set(inner) => format!("repeated {}", glossa_type_to_proto(inner)), // repeated acts like set in proto
        GlossaType::Map(k, v) => format!(
            "map<{}, {}>",
            glossa_type_to_proto(k),
            glossa_type_to_proto(v)
        ),
        GlossaType::Option(inner) => glossa_type_to_proto(inner),
        // By default string is a good fallback for unknown JSON-like types
        _ => "string".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_proto() {
        assert_eq!(glossa_type_to_proto(&GlossaType::Number), "int64");
        assert_eq!(glossa_type_to_proto(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_proto(&GlossaType::Boolean), "bool");
        assert_eq!(
            glossa_type_to_proto(&GlossaType::List(Box::new(GlossaType::Number))),
            "repeated int64"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Set(Box::new(GlossaType::String))),
            "repeated string"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "map<string, int64>"
        );
        assert_eq!(
            glossa_type_to_proto(&GlossaType::Option(Box::new(GlossaType::Number))),
            "int64"
        );
        assert_eq!(glossa_type_to_proto(&GlossaType::Unknown), "string");
    }
}
