//! The Mime (ὁ Μῖμος) - Mock Data Generator
//!
//! This module implements the "Mime" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and automatically generates mock
//! instantiations of those structs with placeholder data.

use crate::semantic::{AnalyzedStatement, GlossaType};
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Mime tool to generate mock data instantiations.
pub fn run_mime(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let source =
        std::fs::read_to_string(input).map_err(|e| miette::miette!("Σφάλμα ἀρχείου: {}", e))?;

    let program = crate::tools::runner::analyze_source(&source)
        .map_err(|e| miette::miette!("Σφάλμα ἀναλύσεως: {}", e))?;

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Mime\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let var_name = name.to_lowercase();
            let _ = writeln!(output, "{} νέον {}", var_name, name);
            for (field_name, field_type) in fields {
                let mock_val = generate_mock_value(field_type);
                let _ = writeln!(output, "    {} // {}", mock_val, field_name);
            }
            output.push_str("ἔστω.\n\n");
        }
    }

    println!();
    println!("Γ Λ Ω Σ Σ Α   M I M E");
    println!("Mock Data");
    println!();
    println!("{}", output.trim());
    println!();

    Ok(())
}

fn generate_mock_value(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "42".to_string(),
        GlossaType::String => "«Δοκιμή»".to_string(),
        GlossaType::Boolean => "ἀληθές".to_string(),
        GlossaType::List(inner) => format!("[{}]", generate_mock_value(inner)),
        GlossaType::Set(inner) => format!("[{}]", generate_mock_value(inner)),
        GlossaType::Map(k, v) => {
            format!("[{} : {}]", generate_mock_value(k), generate_mock_value(v))
        }
        GlossaType::Option(inner) => {
            format!("τί {}", generate_mock_value(inner))
        }
        GlossaType::Result(inner, _) => {
            format!("ἐπιτυχία {}", generate_mock_value(inner))
        }
        _ => "«Ἄγνωστον»".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_mock_value() {
        assert_eq!(generate_mock_value(&GlossaType::Number), "42");
        assert_eq!(generate_mock_value(&GlossaType::String), "«Δοκιμή»");
        assert_eq!(generate_mock_value(&GlossaType::Boolean), "ἀληθές");
        assert_eq!(
            generate_mock_value(&GlossaType::Option(Box::new(GlossaType::Number))),
            "τί 42"
        );
        assert_eq!(
            generate_mock_value(&GlossaType::Result(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "ἐπιτυχία «Δοκιμή»"
        );
    }
}

#[cfg(test)]
mod coverage_tests {
    use super::*;

    #[test]
    fn test_generate_mock_value_collections() {
        assert_eq!(
            generate_mock_value(&GlossaType::List(Box::new(GlossaType::Number))),
            "[42]"
        );
        assert_eq!(
            generate_mock_value(&GlossaType::Set(Box::new(GlossaType::String))),
            "[«Δοκιμή»]"
        );
        assert_eq!(
            generate_mock_value(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "[«Δοκιμή» : 42]"
        );
        assert_eq!(generate_mock_value(&GlossaType::Unknown), "«Ἄγνωστον»");
    }
}
