use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::Status;
use crate::tools::load_source;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::path::Path;

/// Run the Papyrus tool on a file
///
/// Reads the source file, compiles it, and generates SQL CREATE TABLE statements.
pub fn run_papyrus(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πάπυρος (Generating SQL Schema)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            // Note: Since `analyze_source` unifies parsing and semantics, we
            // map it to a generic analysis error.
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("-- Auto-generated by ΓΛΩΣΣΑ Papyrus\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            output.push_str(&format!("CREATE TABLE {} (\n", name));
            for (i, (field_name, field_type)) in fields.iter().enumerate() {
                let sql_type = glossa_type_to_sql(field_type);
                let comma = if i < fields.len() - 1 { "," } else { "" };
                output.push_str(&format!("    {} {}{}\n", field_name, sql_type, comma));
            }
            output.push_str(");\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P A P Y R U S".bold().cyan());
    println!("   {}", "SQL Schema".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("SQL Schema")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```sql\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_sql(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "BIGINT NOT NULL".to_string(),
        GlossaType::String => "TEXT NOT NULL".to_string(),
        GlossaType::Boolean => "BOOLEAN NOT NULL".to_string(),
        GlossaType::List(_) => "JSONB NOT NULL".to_string(),
        GlossaType::Set(_) => "JSONB NOT NULL".to_string(),
        GlossaType::Map(_, _) => "JSONB NOT NULL".to_string(),
        GlossaType::Option(inner) => {
            // Remove the NOT NULL constraint for Option types
            let inner_sql = glossa_type_to_sql(inner);
            inner_sql.replace(" NOT NULL", "")
        }
        _ => "JSONB".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_sql() {
        assert_eq!(glossa_type_to_sql(&GlossaType::Number), "BIGINT NOT NULL");
        assert_eq!(glossa_type_to_sql(&GlossaType::String), "TEXT NOT NULL");
        assert_eq!(glossa_type_to_sql(&GlossaType::Boolean), "BOOLEAN NOT NULL");
        assert_eq!(
            glossa_type_to_sql(&GlossaType::List(Box::new(GlossaType::Number))),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Set(Box::new(GlossaType::Number))),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Option(Box::new(GlossaType::Number))),
            "BIGINT"
        );
        assert_eq!(glossa_type_to_sql(&GlossaType::Unknown), "JSONB");
    }
}
