//! The Papyrus (ὁ Πάπυρος) - SQL Schema Generator
//!
//! This module implements the "Papyrus" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into SQL `CREATE TABLE` statements.
//!
//! # Purpose
//!
//! Ancient records were kept on papyrus. In modern systems, we use databases.
//! This tool bridges the gap by automatically generating PostgreSQL-compatible schema
//! definitions directly from your ΓΛΩΣΣΑ structures.
//!
//! # How it Works
//!
//! The [`run_papyrus`](crate::tools::papyrus::run_papyrus) function orchestrates the process:
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to SQL types (`BIGINT`, `TEXT`, etc.).
//! 4. Outputs formatted SQL code to the terminal using a stylish, colorful table.
use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Papyrus tool to generate SQL schemas from Glossa types.
///
/// The Papyrus (Πάπυρος) tool reads the provided source file, compiles it, and automatically
/// generates corresponding SQL `CREATE TABLE` statements for any type definitions found.
///
/// # Examples
///
/// ```rust,no_run
/// use glossa::tools::papyrus::run_papyrus;
/// use std::path::Path;
///
/// let input = Path::new("schema.γλ");
/// if let Err(e) = run_papyrus(&input) {
///     eprintln!("Schema generation failed: {}", e);
/// }
/// ```
///
/// # Errors
///
/// Returns a [`miette::Result`] if the file cannot be read, or if there is a parsing
/// or semantic analysis error during compilation.
pub fn run_papyrus(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πάπυρος (Generating SQL Schema)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            // Note: Since `analyze_source` unifies parsing and semantics, we
            // map it to a generic analysis error.
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    let mut output = String::new();
    output.push_str("-- Auto-generated by ΓΛΩΣΣΑ Papyrus\n\n");
    let mut schemas_summary = Vec::new();

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            // ⚡ Bolt Optimization: Eliminated `format!` allocations by writing directly to `output`
            let _ = writeln!(output, "CREATE TABLE {} (", name);
            let mut field_summaries = Vec::new();
            for (i, (field_name, field_type)) in fields.iter().enumerate() {
                let sql_type = glossa_type_to_sql(field_type);
                let comma = if i < fields.len() - 1 { "," } else { "" };
                let _ = writeln!(output, "    {} {}{}", field_name, sql_type, comma);
                field_summaries.push(format!("{} ({})", field_name, sql_type));
            }
            output.push_str(");\n\n");
            schemas_summary.push((name.clone(), field_summaries));
        }
    }

    let out_path = input.with_extension("sql");
    if let Err(e) = std::fs::write(&out_path, &output) {
        let err_msg = format!("Failed to write SQL file: {}", e);
        status.error(&err_msg);
        return Err(miette::miette!(err_msg));
    }

    status.success();

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P A P Y R U S".bold().cyan());
    println!("   {}", "SQL Schema Summary".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("Table Name")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
        Cell::new("Columns")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    if schemas_summary.is_empty() {
        table.add_row(vec![
            Cell::new("No tables found").fg(Color::DarkGrey),
            Cell::new("-").fg(Color::DarkGrey),
        ]);
    } else {
        for (name, fields) in schemas_summary {
            table.add_row(vec![
                Cell::new(name).fg(Color::Green),
                Cell::new(fields.join("\n")),
            ]);
        }
    }

    println!("{table}");
    println!(
        "   {}",
        format!("💾 Saved raw SQL to: {}", out_path.display()).dim()
    );
    println!();

    Ok(())
}

fn glossa_type_to_sql(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "BIGINT NOT NULL".to_string(),
        GlossaType::String => "TEXT NOT NULL".to_string(),
        GlossaType::Boolean => "BOOLEAN NOT NULL".to_string(),
        GlossaType::List(_) => "JSONB NOT NULL".to_string(),
        GlossaType::Set(_) => "JSONB NOT NULL".to_string(),
        GlossaType::Map(_, _) => "JSONB NOT NULL".to_string(),
        GlossaType::Option(inner) => {
            // Remove the NOT NULL constraint for Option types
            let inner_sql = glossa_type_to_sql(inner);
            inner_sql.replace(" NOT NULL", "")
        }
        _ => "JSONB".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_sql() {
        assert_eq!(glossa_type_to_sql(&GlossaType::Number), "BIGINT NOT NULL");
        assert_eq!(glossa_type_to_sql(&GlossaType::String), "TEXT NOT NULL");
        assert_eq!(glossa_type_to_sql(&GlossaType::Boolean), "BOOLEAN NOT NULL");
        assert_eq!(
            glossa_type_to_sql(&GlossaType::List(Box::new(GlossaType::Number))),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Set(Box::new(GlossaType::Number))),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "JSONB NOT NULL"
        );
        assert_eq!(
            glossa_type_to_sql(&GlossaType::Option(Box::new(GlossaType::Number))),
            "BIGINT"
        );
        assert_eq!(glossa_type_to_sql(&GlossaType::Unknown), "JSONB");
    }
}
