//! The Prophet (ὁ Προφήτης) - TypeScript Generator
//!
//! This module implements the "Prophet" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript interface statements.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Prophet tool to generate TypeScript interfaces from Glossa types.
pub fn run_prophet(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Προφήτης (Generating TypeScript)", "🔮");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Prophet\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                // Make option fields optional in TS
                let is_optional = matches!(field_type, GlossaType::Option(_));
                let opt_marker = if is_optional { "?" } else { "" };
                let _ = writeln!(output, "    {}{}: {};", field_name, opt_marker, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P R O P H E T".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Interfaces")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => format!("Map<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v)),
        GlossaType::Option(inner) => glossa_type_to_ts(inner),
        GlossaType::Result(ok, _err) => glossa_type_to_ts(ok),
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { params, returns } => {
            let mut p_str = String::new();
            for (i, param) in params.iter().enumerate() {
                if i > 0 {
                    p_str.push_str(", ");
                }
                let _ = write!(p_str, "arg{}: {}", i, glossa_type_to_ts(param));
            }
            format!("({}) => {}", p_str, glossa_type_to_ts(returns))
        }
        GlossaType::Unit => "void".to_string(),
        GlossaType::Unknown => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;


    #[test]
    fn test_run_prophet_success() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("schema.γλ");
        // Valid glossa types: ὄνομα (String), ἀριθμός (Number). Let's use standard properties.
        std::fs::write(&input_path, "εἶδος Χρήστης ὁρίζειν { ὄνομα ὀνόματος. ἡλικία ἀριθμοῦ. }.").unwrap();

        let result = run_prophet(&input_path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_run_prophet_file_not_found() {
        let input_path = Path::new("nonexistent_prophet_file.γλ");
        let result = run_prophet(input_path);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("οὐχ εὑρέθη"));
    }

    #[test]
    fn test_run_prophet_analysis_error() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("error.γλ");
        // Syntax error
        std::fs::write(&input_path, "not valid glossa").unwrap();

        let result = run_prophet(&input_path);
        assert!(result.is_err());
    }

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Map<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
