//! The Proteus (ὁ Πρωτεύς) - TypeScript Interface Generator
//!
//! This module implements the "Proteus" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface`
//! definitions.
//!
//! # Purpose
//!
//! Proteus was the prophetic old man of the sea who could change his shape at will.
//! This tool embodies that spirit by transforming Glossa types into modern web frontend types.
//!
//! # How it Works
//!
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to TypeScript types (`number`, `string`, etc.).
//! 4. Outputs formatted TypeScript code to the terminal using a stylish, colorful table.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Proteus tool to generate TypeScript interfaces from Glossa types.
///
/// The Proteus (Πρωτεύς) tool reads the provided source file, compiles it, and automatically
/// generates corresponding TypeScript `interface` definitions for any type definitions found.
pub fn run_proteus(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πρωτεύς (Generating TypeScript Interfaces)", "🌊");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Proteus\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            // Normalize the struct name to ascii to ensure standard TS behavior if it was parsed as Greek
            // Normally AST outputs are checked against lowercase unaccented strings as per memory:
            // "In Glossa, the compiler normalizes Greek identifiers (variables, type names) into lowercase,
            // unaccented strings during semantic analysis."
            // But we might want to capitalize the first letter for TypeScript interfaces:
            let ts_name = name.to_string(); // we will keep it as the analyzer gave us, but maybe capitalize the first char if needed
            let mut capitalized_name = ts_name.clone();
            if let Some(c) = ts_name.chars().next() {
                capitalized_name = c.to_uppercase().collect::<String>() + &ts_name[c.len_utf8()..];
            }

            let _ = writeln!(output, "export interface {} {{", capitalized_name);
            for (field_name, field_type) in fields.iter() {
                let (ts_type, is_optional) = glossa_type_to_ts(field_type);
                let optional_marker = if is_optional { "?" } else { "" };
                let _ = writeln!(
                    output,
                    "    {}{}: {};",
                    field_name, optional_marker, ts_type
                );
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P R O T E U S".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Interfaces")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> (String, bool) {
    match g_type {
        GlossaType::Number => ("number".to_string(), false),
        GlossaType::String => ("string".to_string(), false),
        GlossaType::Boolean => ("boolean".to_string(), false),
        GlossaType::List(inner) => {
            let (inner_type, _) = glossa_type_to_ts(inner);
            (format!("{}[]", inner_type), false)
        }
        GlossaType::Set(inner) => {
            let (inner_type, _) = glossa_type_to_ts(inner);
            // Representing Set as an array in TS interface is common, or `Set<T>`
            (format!("Set<{}>", inner_type), false)
        }
        GlossaType::Map(key, value) => {
            let (key_type, _) = glossa_type_to_ts(key);
            let (value_type, _) = glossa_type_to_ts(value);
            // Record<K, V> is typical. Note: K must be string/number/symbol in TS usually, but Record allows more in modern TS
            (format!("Record<{}, {}>", key_type, value_type), false)
        }
        GlossaType::Option(inner) => {
            let (inner_type, _) = glossa_type_to_ts(inner);
            (inner_type, true)
        }
        GlossaType::Struct { name, .. } => {
            // In Glossa's AST, type names are normalized. Let's capitalize the first letter.
            let ts_name = name.to_string();
            let mut capitalized_name = ts_name.clone();
            if let Some(c) = ts_name.chars().next() {
                capitalized_name = c.to_uppercase().collect::<String>() + &ts_name[c.len_utf8()..];
            }
            (capitalized_name, false)
        }
        // Glossa function
        GlossaType::Function { params, returns } => {
            let mut ts_params = Vec::new();
            for (i, param) in params.iter().enumerate() {
                let (param_type, _) = glossa_type_to_ts(param);
                ts_params.push(format!("arg{}: {}", i, param_type));
            }
            let (return_type, _) = if let GlossaType::Unit = **returns {
                ("void".to_string(), false)
            } else {
                glossa_type_to_ts(returns)
            };
            (
                format!("({}) => {}", ts_params.join(", "), return_type),
                false,
            )
        }
        _ => ("any".to_string(), false),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Number),
            ("number".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::String),
            ("string".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Boolean),
            ("boolean".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            ("number[]".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            ("Set<number>".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            ("Record<string, number>".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            ("number".to_string(), true)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "user".into(),
                gender: Gender::Masculine,
                fields: vec![]
            }),
            ("User".to_string(), false)
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function {
                params: vec![GlossaType::Number, GlossaType::String],
                returns: Box::new(GlossaType::Boolean)
            }),
            ("(arg0: number, arg1: string) => boolean".to_string(), false)
        );
    }
}
