//! The Proxenos (ὁ Πρόξενος) - TypeScript Interface Generator
//!
//! This module implements the "Proxenos" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `export interface` statements.
//!
//! # Purpose
//!
//! The "Proxenos" (consul or ambassador) represents the connection between states.
//! This tool bridges ΓΛΩΣΣΑ with the frontend ecosystem by automatically generating
//! TypeScript definitions from your ΓΛΩΣΣΑ structures.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Proxenos tool to generate TypeScript interfaces from Glossa types.
///
/// The Proxenos (Πρόξενος) tool reads the provided source file, compiles it, and automatically
/// generates corresponding TypeScript `export interface` statements for any type definitions found.
///
/// # Examples
///
/// ```rust,no_run
/// use glossa::tools::proxenos::run_proxenos;
/// use std::path::Path;
///
/// let input = Path::new("schema.γλ");
/// if let Err(e) = run_proxenos(&input) {
///     eprintln!("Interface generation failed: {}", e);
/// }
/// ```
///
/// # Errors
///
/// Returns a [`miette::Result`] if the file cannot be read, or if there is a parsing
/// or semantic analysis error during compilation.
pub fn run_proxenos(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πρόξενος (Generating TypeScript Interfaces)", "🤝");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Proxenos\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                let optional = if matches!(field_type, GlossaType::Option(_)) {
                    "?"
                } else {
                    ""
                };
                let _ = writeln!(output, "    {}{}: {};", field_name, optional, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    let mut table = Table::new();
    table
        .load_preset(presets::UTF8_FULL)
        .set_content_arrangement(comfy_table::ContentArrangement::Dynamic)
        .set_header(vec![
            Cell::new("TypeScript Interfaces (Πρόξενος)")
                .fg(Color::Cyan)
                .add_attribute(Attribute::Bold),
        ]);

    let display_str = if output.trim() == "// Auto-generated by ΓΛΩΣΣΑ Proxenos" {
        "No type definitions (εἶδος) found in the program.".to_string()
    } else {
        output
    };

    table.add_row(vec![Cell::new(display_str).fg(Color::Yellow)]);

    println!("\n{}", table);

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => glossa_type_to_ts(inner), // Option handled via '?' in field decl
        GlossaType::Result(ok, _err) => glossa_type_to_ts(ok), // Simple mapping for now
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { params, returns } => {
            let params_ts = params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("arg{}: {}", i, glossa_type_to_ts(p)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({}) => {}", params_ts, glossa_type_to_ts(returns))
        }
        GlossaType::Unit => "void".to_string(),
        GlossaType::Unknown => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "string"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: Gender::Masculine,
                fields: vec![]
            }),
            "User"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");

        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function {
                params: vec![GlossaType::Number, GlossaType::String],
                returns: Box::new(GlossaType::Boolean)
            }),
            "(arg0: number, arg1: string) => boolean"
        );
    }
}
