//! The Ptolemy (ὁ Πτολεμαῖος) - TypeScript Definition Generator
//!
//! This module implements the "Ptolemy" tool, which inspects the type definitions
//! (`εἶδος`) and functions (`ἔργα`) within a ΓΛΩΣΣΑ program and translates them into TypeScript
//! definition (`.d.ts`) files.
//!
//! # Purpose
//!
//! Ptolemy mapped the stars and geography of the ancient world. This tool maps the
//! semantic structure of a ΓΛΩΣΣΑ program into a modern ecosystem (TypeScript), enabling
//! seamless interoperability.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Ptolemy tool to generate TypeScript definitions from Glossa types and functions.
pub fn run_ptolemy(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πτολεμαῖος (Generating TypeScript Definitions)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Ptolemy\n");
    output.push_str("// TypeScript Definitions\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                let _ = writeln!(output, "    {}: {};", field_name, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    for func in program.scope.functions() {
        // Skip the main function equivalent if any, though Glossa doesn't strictly have one.
        // We will just export all functions.
        let mut params_str = String::new();
        for (i, param_type) in func.param_types.iter().enumerate() {
            if i > 0 {
                params_str.push_str(", ");
            }
            let ts_type = glossa_type_to_ts(param_type);
            let _ = write!(params_str, "arg{}: {}", i, ts_type);
        }

        let ret_type = func
            .return_type
            .as_ref()
            .map(glossa_type_to_ts)
            .unwrap_or_else(|| "void".to_string());

        let _ = writeln!(
            output,
            "export declare function {}({}): {};\n",
            func.name, params_str, ret_type
        );
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P T O L E M Y".bold().cyan());
    println!("   {}", "TypeScript Definitions".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript (.d.ts)")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    let output_path = input.with_extension("d.ts");
    if let Err(e) = std::fs::write(&output_path, &output) {
        return Err(miette::miette!("Failed to write definition file: {}", e));
    }

    println!(
        "   {} {}",
        "Saved to:".bold(),
        output_path.display().to_string().cyan()
    );
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => {
            format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number | string"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
