//! The Pythia (ἡ Πυθία) - GraphQL Schema Generator
//!
//! This module implements the "Pythia" tool, which inspects the type definitions
//! (`εἶδος`) and trait definitions (`χαρακτήρ`) within a ΓΛΩΣΣΑ program and translates them
//! into GraphQL schema definitions (`type` and `interface`).
//!
//! # Purpose
//!
//! The Oracle at Delphi (Pythia) interpreted the divine will and delivered prophecies.
//! In modern systems, GraphQL schemas serve as a similar contract between frontend and backend.
//! This tool bridges the gap by automatically generating GraphQL schemas directly from your
//! ΓΛΩΣΣΑ structures and traits.
//!
//! # How it Works
//!
//! The [`run_pythia`](crate::tools::pythia::run_pythia) function orchestrates the process:
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` and `TraitDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to GraphQL types (`Int`, `String`, etc.).
//! 4. Outputs formatted GraphQL code to the terminal using a stylish, colorful table.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Pythia tool to generate GraphQL schemas from Glossa types and traits.
///
/// The Pythia (Πυθία) tool reads the provided source file, compiles it, and automatically
/// generates corresponding GraphQL `type` and `interface` statements.
pub fn run_pythia(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Πυθία (Generating GraphQL Schema)", "🔮");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("# Auto-generated by ΓΛΩΣΣΑ Pythia\n\n");

    let mut generated_something = false;

    for stmt in &program.statements {
        match stmt {
            AnalyzedStatement::TypeDefinition { name, fields } => {
                generated_something = true;
                let _ = writeln!(output, "type {} {{", name);
                for (field_name, field_type) in fields {
                    let graphql_type = glossa_type_to_graphql(field_type);
                    let _ = writeln!(output, "  {}: {}", field_name, graphql_type);
                }
                output.push_str("}\n\n");
            }
            AnalyzedStatement::TraitDefinition { name, methods } => {
                generated_something = true;
                let _ = writeln!(output, "interface {} {{", name);
                for method in methods {
                    // Start method signature
                    let _ = write!(output, "  {}(", method.name);

                    // Add parameters
                    for (i, (param_name, param_type)) in method.params.iter().enumerate() {
                        let graphql_type = glossa_type_to_graphql(param_type);

                        let comma = if i < method.params.len() - 1 {
                            ", "
                        } else {
                            ""
                        };
                        let _ = write!(output, "{}: {}{}", param_name, graphql_type, comma);
                    }

                    // Add return type
                    let return_type = if let Some(t) = &method.return_type {
                        glossa_type_to_graphql(t)
                    } else {
                        "Void".to_string() // Meaningless in standard GraphQL, but conceptually fits
                    };

                    let _ = writeln!(output, "): {}", return_type);
                }
                output.push_str("}\n\n");
            }
            _ => {}
        }
    }

    if !generated_something {
        output.push_str("# No type or trait definitions found in the source file.\n");
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   P Y T H I A".bold().magenta());
    println!("   {}", "GraphQL Schema".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("GraphQL Schema")
            .add_attribute(Attribute::Bold)
            .fg(Color::Magenta),
    ]);

    let formatted_code = format!("```graphql\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_graphql(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "Int!".to_string(),
        GlossaType::String => "String!".to_string(),
        GlossaType::Boolean => "Boolean!".to_string(),
        GlossaType::List(inner) | GlossaType::Set(inner) => {
            format!("[{}]!", glossa_type_to_graphql(inner))
        }
        GlossaType::Option(inner) => {
            let inner_gql = glossa_type_to_graphql(inner);
            // Remove the trailing '!' to make it nullable
            inner_gql.replace("!", "")
        }
        _ => "JSON".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_graphql() {
        assert_eq!(glossa_type_to_graphql(&GlossaType::Number), "Int!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::String), "String!");
        assert_eq!(glossa_type_to_graphql(&GlossaType::Boolean), "Boolean!");
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::List(Box::new(GlossaType::Number))),
            "[Int!]!"
        );
        assert_eq!(
            glossa_type_to_graphql(&GlossaType::Option(Box::new(GlossaType::Number))),
            "Int"
        );
        assert_eq!(glossa_type_to_graphql(&GlossaType::Unknown), "JSON");
    }

    #[test]
    fn test_run_pythia_success() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("pythia_test.gl");
        std::fs::write(&input_path, "εἶδος Χρήστης ὁρίζειν { ὄνομα ὀνόματος. }.").unwrap();

        let result = run_pythia(&input_path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_run_pythia_missing_file() {
        let input_path = Path::new("missing_pythia_file.gl");
        let result = run_pythia(input_path);
        assert!(result.is_err());
    }

    #[test]
    fn test_run_pythia_invalid_syntax() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("invalid_pythia.gl");
        std::fs::write(&input_path, "not valid greek").unwrap();
        let result = run_pythia(&input_path);
        assert!(result.is_err());
    }
}
