//! The Scribe (ὁ Γραμματεύς) - TypeScript Definition Generator
//!
//! This module implements the "Scribe" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface` definitions.
//!
//! # Purpose
//!
//! Ancient scholars shared their knowledge across borders. The Scribe does the same
//! by bridging the gap between ΓΛΩΣΣΑ structures and the modern Web. It automatically
//! generates TypeScript (`.d.ts`) definitions directly from your ΓΛΩΣΣΑ structs.
//!
//! # How it Works
//!
//! The [`run_scribe`](crate::tools::scribe::run_scribe) function orchestrates the process:
//! 1. Parses and semantically analyzes the source code.
//! 2. Scans the Abstract Syntax Tree for `TypeDefinition` nodes.
//! 3. Maps ΓΛΩΣΣΑ types (`ἀριθμοῦ`, `ὀνόματος`, etc.) to TypeScript types (`number`, `string`, etc.).
//! 4. Outputs formatted TypeScript code to the terminal using a stylish, colorful table.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Scribe tool to generate TypeScript interfaces from Glossa types.
///
/// The Scribe (Γραμματεύς) tool reads the provided source file, compiles it, and automatically
/// generates corresponding TypeScript `interface` statements for any type definitions found.
///
/// # Errors
///
/// Returns a [`miette::Result`] if the file cannot be read, or if there is a parsing
/// or semantic analysis error during compilation.
pub fn run_scribe(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Γραμματεύς (Generating TypeScript)", "✍️ ");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Scribe\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                let optional_marker = if matches!(field_type, GlossaType::Option(_)) {
                    "?"
                } else {
                    ""
                };
                let _ = writeln!(
                    output,
                    "    {}{}: {};",
                    field_name, optional_marker, ts_type
                );
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   S C R I B E".bold().cyan());
    println!("   {}", "TypeScript Definitions".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript (.d.ts)")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => glossa_type_to_ts(inner),
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::morphology::Gender;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: Gender::Neuter,
                fields: vec![]
            }),
            "User"
        );
    }
}
