//! The Scribe (ὁ Γραμματεύς) - TypeScript Interface Generator
//!
//! This module implements the "Scribe" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface` statements.
//!
//! # Purpose
//!
//! This tool bridges the gap by automatically generating TypeScript
//! definitions directly from your ΓΛΩΣΣΑ structures.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

pub fn run_scribe(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Γραμματεύς (Generating TypeScript Interfaces)", "📜");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Scribe\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                let _ = writeln!(output, "    {}: {};", field_name, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   S C R I B E".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("Generated TypeScript")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(glossa_type: &GlossaType) -> String {
    match glossa_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("{}[]", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => format!("Map<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v)),
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err)),
        GlossaType::Unit => "void".to_string(),
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { .. } => "Function".to_string(),
        GlossaType::Unknown => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::String))),
            "string[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
    }

    #[test]
    fn test_glossa_type_to_ts_extended() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(Box::new(GlossaType::String), Box::new(GlossaType::Number))),
            "Map<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(Box::new(GlossaType::String), Box::new(GlossaType::Number))),
            "string | number"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct { name: "User".into(), gender: crate::morphology::Gender::Masculine, fields: vec![] }),
            "User"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Function { params: vec![], returns: Box::new(GlossaType::Unit) }),
            "Function"
        );
    }
}
