use miette::Result;
use std::path::Path;

use crate::semantic::AnalyzedStatement;
use crate::semantic::GlossaType;
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use crossterm::style::Stylize;
use std::fmt::Write;

pub fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => {
            format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => format!("{} | null", glossa_type_to_ts(inner)),
        GlossaType::Result(ok, err) => {
            format!("{} | {}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        GlossaType::Function { params, returns } => {
            let mut ts_params = String::new();
            for (i, param) in params.iter().enumerate() {
                if i > 0 {
                    ts_params.push_str(", ");
                }
                ts_params.push_str(&format!("arg{}: {}", i, glossa_type_to_ts(param)));
            }
            format!("({}) => {}", ts_params, glossa_type_to_ts(returns))
        }
        GlossaType::Unit => "void".to_string(),
        GlossaType::Unknown => "any".to_string(),
    }
}

pub fn run_sculptor(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Γλύπτης (Generating TypeScript)", "🗿");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str(
        "// Auto-generated by ΓΛΩΣΣΑ Sculptor

",
    );

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                let _ = writeln!(output, "    {}: {};", field_name, ts_type);
            }
            output.push_str(
                "}

",
            );
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   S C U L P T O R".bold().cyan());
    println!("   {}", "TypeScript Interfaces".italic().dim());
    println!();

    let mut table = comfy_table::Table::new();
    table.load_preset(comfy_table::presets::UTF8_FULL);

    table.set_header(vec![
        comfy_table::Cell::new("TypeScript Interfaces")
            .add_attribute(comfy_table::Attribute::Bold)
            .fg(comfy_table::Color::Cyan),
    ]);

    let formatted_code = format!(
        "```typescript
{}
```",
        output.trim()
    );
    table.add_row(vec![comfy_table::Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic::GlossaType;

    #[test]
    fn test_glossa_type_to_ts_basic() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unit), "void");
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }

    #[test]
    fn test_glossa_type_to_ts_composite() {
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number | null"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Result(
                Box::new(GlossaType::Number),
                Box::new(GlossaType::String)
            )),
            "number | string"
        );
    }

    #[test]
    fn test_glossa_type_to_ts_struct() {
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Struct {
                name: "User".into(),
                gender: crate::morphology::Gender::Masculine,
                fields: vec![]
            }),
            "User"
        );
    }

    #[test]
    fn test_run_sculptor_success() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("test_sculptor.γλ");
        {
            use std::io::Write;
            let mut f = std::fs::File::create(&input_path).unwrap();
            f.write_all("εἶδος Χρήστης ὁρίζειν {\n    ὄνομα ὀνόματος.\n}.\n".as_bytes())
                .unwrap();
        }

        let result = run_sculptor(&input_path);
        assert!(result.is_ok());
    }

    #[test]
    fn test_run_sculptor_file_not_found() {
        let path = Path::new("non_existent_file.γλ");
        let result = run_sculptor(path);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("οὐχ εὑρέθη"));
    }

    #[test]
    fn test_run_sculptor_parse_error() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("test_sculptor_parse_error.γλ");
        std::fs::write(&input_path, b"invalid syntax").unwrap();

        let result = run_sculptor(&input_path);
        assert!(result.is_err());
    }

    #[test]
    fn test_run_sculptor_semantic_error() {
        let dir = tempfile::tempdir().unwrap();
        let input_path = dir.path().join("test_sculptor_semantic_error.γλ");
        // Valid syntax, semantic error (reassigning undefined variable)
        std::fs::write(&input_path, "ψ 10 γίγνεται.").unwrap();

        let result = run_sculptor(&input_path);
        assert!(result.is_err());
    }
}
