//! The Sculptor (ὁ Γλύπτης) - TypeScript Interface Generator
//!
//! This module implements the "Sculptor" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `export interface` statements.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Sculptor tool to generate TypeScript interfaces from Glossa types.
pub fn run_sculptor(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    println!("⚡ Γλύπτης (Generating TypeScript)...");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("✕ Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("✕ Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    println!("✓ Done");

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Sculptor\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields {
                let ts_type = glossa_type_to_ts(field_type);
                if let GlossaType::Option(inner) = field_type {
                     let inner_ts = glossa_type_to_ts(inner);
                     let _ = writeln!(output, "    {}?: {};", field_name, inner_ts);
                } else {
                     let _ = writeln!(output, "    {}: {};", field_name, ts_type);
                }
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   Γ Λ Ω Σ Σ Α   S C U L P T O R");
    println!("   TypeScript Interfaces");
    println!();
    println!("```typescript\n{}\n```", output.trim());
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) | GlossaType::Set(inner) => {
            format!("{}[]", glossa_type_to_ts(inner))
        }
        GlossaType::Map(k, v) => {
            let key_type = match **k {
                GlossaType::String | GlossaType::Number => glossa_type_to_ts(k),
                _ => "string".to_string(),
            };
            format!("Record<{}, {}>", key_type, glossa_type_to_ts(v))
        }
        GlossaType::Option(inner) => glossa_type_to_ts(inner),
        GlossaType::Result(ok, err) => {
            format!("{{ ok: true, value: {} }} | {{ ok: false, error: {} }}", glossa_type_to_ts(ok), glossa_type_to_ts(err))
        }
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "number[]"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
