//! The Sibyl (ἡ Σίβυλλα) - TypeScript Declaration Generator
//!
//! This module implements the "Sibyl" tool, which inspects the type definitions
//! (`εἶδος`) within a ΓΛΩΣΣΑ program and translates them into TypeScript `interface` definitions.

use crate::semantic::{AnalyzedStatement, GlossaType};
use crate::tools::runner::load_source;
use crate::tools::ui::Status;
use comfy_table::{Attribute, Cell, Color, Table, presets};
use crossterm::style::Stylize;
use miette::Result;
use std::fmt::Write;
use std::path::Path;

/// Runs the Sibyl tool to generate TypeScript interfaces from Glossa types.
pub fn run_sibyl(input: &Path) -> Result<()> {
    if !input.exists() {
        return Err(miette::miette!("Ἀρχεῖον οὐχ εὑρέθη: {}", input.display()));
    }

    let status = Status::start_with_symbol("Σίβυλλα (Generating TypeScript Types)", "🔮");

    let source = match load_source(input) {
        Ok(s) => s,
        Err(e) => {
            status.error("Σφάλμα ἀρχείου (File Error)");
            return Err(e);
        }
    };

    let program = match crate::tools::runner::analyze_source(&source) {
        Ok(p) => p,
        Err(e) => {
            status.error("Σφάλμα ἀναλύσεως (Analysis Error)");
            return Err(e);
        }
    };

    status.success();

    let mut output = String::new();
    output.push_str("// Auto-generated by ΓΛΩΣΣΑ Sibyl\n\n");

    for stmt in &program.statements {
        if let AnalyzedStatement::TypeDefinition { name, fields } = stmt {
            let _ = writeln!(output, "export interface {} {{", name);
            for (field_name, field_type) in fields.iter() {
                let ts_type = glossa_type_to_ts(field_type);
                let optional_marker = if matches!(field_type, GlossaType::Option(_)) { "?" } else { "" };
                let _ = writeln!(output, "    {}{}: {};", field_name, optional_marker, ts_type);
            }
            output.push_str("}\n\n");
        }
    }

    println!();
    println!("   {}", "Γ Λ Ω Σ Σ Α   S I B Y L".bold().cyan());
    println!("   {}", "TypeScript Types".italic().dim());
    println!();

    let mut table = Table::new();
    table.load_preset(presets::UTF8_FULL);

    table.set_header(vec![
        Cell::new("TypeScript Declarations")
            .add_attribute(Attribute::Bold)
            .fg(Color::Cyan),
    ]);

    let formatted_code = format!("```typescript\n{}\n```", output.trim());
    table.add_row(vec![Cell::new(formatted_code)]);

    println!("{table}");
    println!();

    Ok(())
}

fn glossa_type_to_ts(g_type: &GlossaType) -> String {
    match g_type {
        GlossaType::Number => "number".to_string(),
        GlossaType::String => "string".to_string(),
        GlossaType::Boolean => "boolean".to_string(),
        GlossaType::List(inner) => format!("Array<{}>", glossa_type_to_ts(inner)),
        GlossaType::Set(inner) => format!("Set<{}>", glossa_type_to_ts(inner)),
        GlossaType::Map(k, v) => format!("Record<{}, {}>", glossa_type_to_ts(k), glossa_type_to_ts(v)),
        GlossaType::Option(inner) => glossa_type_to_ts(inner),
        GlossaType::Struct { name, .. } => name.to_string(),
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glossa_type_to_ts() {
        assert_eq!(glossa_type_to_ts(&GlossaType::Number), "number");
        assert_eq!(glossa_type_to_ts(&GlossaType::String), "string");
        assert_eq!(glossa_type_to_ts(&GlossaType::Boolean), "boolean");
        assert_eq!(
            glossa_type_to_ts(&GlossaType::List(Box::new(GlossaType::Number))),
            "Array<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Set(Box::new(GlossaType::Number))),
            "Set<number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Map(
                Box::new(GlossaType::String),
                Box::new(GlossaType::Number)
            )),
            "Record<string, number>"
        );
        assert_eq!(
            glossa_type_to_ts(&GlossaType::Option(Box::new(GlossaType::Number))),
            "number"
        );
        assert_eq!(glossa_type_to_ts(&GlossaType::Unknown), "any");
    }
}
